// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:b0d91fb62af08d6df7113b91209e9869bee112506d29e5da63e938bfffebaadf
fn main() {
    let crate_dir = std::env::var("CARGO_MANIFEST_DIR").unwrap();
    cbindgen::generate(crate_dir)
        .expect("Unable to generate C bindings")
        .write_to_file("include/kreuzberg.h");

    let go_include_dir = std::path::Path::new("../../../packages/go/v5/include");
    std::fs::create_dir_all(go_include_dir).expect("Unable to create Go include directory");
    std::fs::copy("include/kreuzberg.h", go_include_dir.join("kreuzberg.h"))
        .expect("Unable to copy header to Go include directory");
}
