# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:b107bc945d7997683fc59b98218482e48ff0b2ea3acf3a8cfcc755c115fa07dd
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# E2e tests for category: document_extractor_management
defmodule E2e.DocumentExtractorManagementTest do
  use ExUnit.Case, async: false

  describe "document_extractors_clear" do
    test "document_extractors_clear" do
      result = Kreuzberg.clear_document_extractors()
    end
  end

  describe "extractors_list" do
    test "extractors_list" do
      result = Kreuzberg.list_document_extractors()
    end
  end
end
