# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:10f69d3922c038c3f3397ab775fa7c70016151a1f97a547ab8ea739f743a5288
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# E2e tests for category: embedding_backend_management
defmodule E2e.EmbeddingBackendManagementTest do
  use ExUnit.Case, async: false

  describe "embedding_backends_clear" do
    test "embedding_backends_clear" do
      result = Xberg.clear_embedding_backends()
    end
  end

  describe "embedding_backends_list" do
    test "embedding_backends_list" do
      result = Xberg.list_embedding_backends()
    end
  end
end
