# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:9f578f2470bbec7549733c73ae6b7d724fd2f5f58441654ef1d408d21e501c7d
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# E2e tests for category: embedding_backend_management
defmodule E2e.EmbeddingBackendManagementTest do
  use ExUnit.Case, async: false

  describe "embedding_backends_clear" do
    test "embedding_backends_clear" do
      result = Kreuzberg.clear_embedding_backends()
    end
  end

  describe "embedding_backends_list" do
    test "embedding_backends_list" do
      result = Kreuzberg.list_embedding_backends()
    end
  end
end
