# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:f1d9a4f3e11a0fb3b3f5a7ba8a0c897768ad230c7d2c8dfef213c1421b13b9fe
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# E2e tests for category: pdf
defmodule E2e.PdfTest do
  use ExUnit.Case, async: false

  describe "render_pdf_page_first" do
    test "render_pdf_page_first" do
      pdf_bytes = File.read!("../../test_documents/pdf/fake_memo.pdf")
      {:ok, result} = Kreuzberg.render_pdf_page_to_png(pdf_bytes, 0)
      assert (is_binary(result) && byte_size(result) >= 100) || (is_list(result) && length(result) >= 100)
    end
  end

  describe "render_pdf_page_out_of_range" do
    test "render_pdf_page_out_of_range" do
      pdf_bytes = File.read!("../../test_documents/pdf/fake_memo.pdf")
      assert {:error, _} = Kreuzberg.render_pdf_page_to_png(pdf_bytes, 999)
    end
  end
end
