# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:3f977ad0c67d45dc13618bc944a117b0cddd1279338a15393e261492c574984a
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# E2e tests for category: post_processor_management
defmodule E2e.PostProcessorManagementTest do
  use ExUnit.Case, async: false

  describe "post_processors_clear" do
    test "post_processors_clear" do
      result = Kreuzberg.clear_post_processors(nil)
    end
  end

  describe "post_processors_list" do
    test "post_processors_list" do
      result = Kreuzberg.list_post_processors(nil)
    end
  end
end
