# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:efd2140ced6a009a9d1d38ddc72b4db276a858d7af7ae2532a69917fe8e14cdc
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# E2e tests for category: renderer_management
defmodule E2e.RendererManagementTest do
  use ExUnit.Case, async: false

  describe "renderers_clear" do
    test "renderers_clear" do
      result = Kreuzberg.clear_renderers()
    end
  end

  describe "renderers_list" do
    test "renderers_list" do
      result = Kreuzberg.list_renderers()
    end
  end
end
