# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:740c5012904701fee6acaa339c14e09b8d6aabec4913ba82b7a4ce9124721264
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# E2e tests for category: reranker_backend_management
defmodule E2e.RerankerBackendManagementTest do
  use ExUnit.Case, async: false

  describe "clear_reranker_backends" do
    test "clear_reranker_backends" do
      result = Kreuzberg.clear_reranker_backends()
    end
  end

  describe "list_reranker_backends" do
    test "list_reranker_backends" do
      result = Kreuzberg.list_reranker_backends()
    end
  end
end
