# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:1ea2e31be2ea3875c4ac7b04e7c0c6025863bc99d4f62123c28991d3b085a679
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# E2e tests for category: summarization
defmodule E2e.SummarizationTest do
  use ExUnit.Case, async: false

  describe "summarization_extractive_smoke" do
    test "summarization_extractive_smoke" do
      {:ok, result} = Kreuzberg.extract_file_sync("../../test_documents/text/book_war_and_peace_1p.txt", config: "{\"summarization\":{\"max_tokens\":80,\"strategy\":\"extractive\"}}")
      assert String.trim(result.mime_type) == "text/plain"
      assert result.summary.text != ""
      assert String.trim(to_string(result.summary.strategy)) == "extractive"
    end
  end
end
