# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:101f93f77893c2c7989723625cc5537a934c702f60a360b93d41055b40c41ceb
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# E2e tests for category: validator_management
defmodule E2e.ValidatorManagementTest do
  use ExUnit.Case, async: false

  describe "validators_clear" do
    test "validators_clear" do
      result = Kreuzberg.clear_validators()
    end
  end

  describe "validators_list" do
    test "validators_list" do
      result = Kreuzberg.list_validators()
    end
  end
end
