// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:efd2140ced6a009a9d1d38ddc72b4db276a858d7af7ae2532a69917fe8e14cdc
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code

using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading.Tasks;
using Xunit;
using Kreuzberg;
using static Kreuzberg.KreuzbergConverter;

namespace Kreuzberg
{
    /// <summary>E2e tests for category: embedding_backend_management.</summary>
    public class EmbeddingBackendManagementTests
    {
            private static readonly JsonSerializerOptions ConfigOptions = new() { Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) }, DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault };

        [Fact]
        public void Test_EmbeddingBackendsClear()
        {
            // Clear all embedding backends and verify list is empty
            KreuzbergConverter.ClearEmbeddingBackends();
        }

        [Fact]
        public void Test_EmbeddingBackendsList()
        {
            // List all registered embedding backends
            var result = KreuzbergConverter.ListEmbeddingBackends();

        }


    }
}
