// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:6a8400ffd6e27c557ffd585458e080034774f33340cc49f53c2cb322a0da85dd
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code

using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading.Tasks;
using Xunit;
using Kreuzberg;
using static Kreuzberg.KreuzbergLib;

namespace Kreuzberg
{
    /// <summary>E2e tests for category: registry_operations.</summary>
    public class RegistryOperationsTests
    {
            private static readonly JsonSerializerOptions ConfigOptions = new() { Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) }, DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault };

        [Fact]
        public void Test_ExtensionsDocx()
        {
            // Get file extensions for DOCX MIME type
            var result = KreuzbergLib.GetExtensionsForMime("application/vnd.openxmlformats-officedocument.wordprocessingml.document");

        }

        [Fact]
        public void Test_ExtensionsHtml()
        {
            // Get file extensions for HTML MIME type
            var result = KreuzbergLib.GetExtensionsForMime("text/html");

        }

        [Fact]
        public void Test_ExtensionsPdf()
        {
            // Get file extensions for PDF MIME type
            var result = KreuzbergLib.GetExtensionsForMime("application/pdf");

        }


    }
}
