// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:f1d9a4f3e11a0fb3b3f5a7ba8a0c897768ad230c7d2c8dfef213c1421b13b9fe
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code

using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading.Tasks;
using Xunit;
using Kreuzberg;
using static Kreuzberg.KreuzbergConverter;

namespace Kreuzberg
{
    /// <summary>E2e tests for category: registry.</summary>
    public class RegistryTests
    {
            private static readonly JsonSerializerOptions ConfigOptions = new() { Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) }, DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault };

        [Fact]
        public void Test_ListDocumentExtractors()
        {
            // List document extractors
            var result = KreuzbergConverter.ListDocumentExtractors();

        }

        [Fact]
        public void Test_ListEmbeddingBackends()
        {
            // List embedding backends
            var result = KreuzbergConverter.ListEmbeddingBackends();

        }

        [Fact]
        public void Test_ListOcrBackends()
        {
            // List OCR backends
            var result = KreuzbergConverter.ListOcrBackends();

        }

        [Fact]
        public void Test_ListPostProcessors()
        {
            // List post-processors
            var result = KreuzbergConverter.ListPostProcessors();

        }

        [Fact]
        public void Test_ListRenderers()
        {
            // List renderers
            var result = KreuzbergConverter.ListRenderers();

        }

        [Fact]
        public void Test_ListValidators()
        {
            // List validators
            var result = KreuzbergConverter.ListValidators();

        }


    }
}
