// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:129f6c78bc96b39658ce61eefcba84c48dda7c11a0dc9f36687849db17ea4295
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
//! E2e tests for category: document_extractor_management

use kreuzberg::{clear_document_extractors, list_document_extractors};

#[test]
fn test_document_extractors_clear() {
    // Clear all document extractors and verify list is empty
    let _ = clear_document_extractors();
}

#[test]
fn test_extractors_list() {
    // List all registered document extractors
    let _ = list_document_extractors();
}
