// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:9f578f2470bbec7549733c73ae6b7d724fd2f5f58441654ef1d408d21e501c7d
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
//! E2e tests for category: embed_extra

use kreuzberg::embed_texts;
use kreuzberg::EmbeddingConfig;

#[test]
fn test_embed_texts_batch() {
    // Batch embed texts
    let texts_json: serde_json::Value = serde_json::from_str(r#"["Hello","World"]"#).unwrap();
    let texts: EmbeddingConfig = serde_json::from_value::<Vec<String>>(texts_json).unwrap();
    let config_json: serde_json::Value =
        serde_json::from_str(r#"{"model":{"name":"balanced","type":"preset"}}"#).unwrap();
    let config: EmbeddingConfig = serde_json::from_value(config_json).unwrap();
    let _ = embed_texts(texts, &config).expect("should succeed");
}
