// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:c9dc9b974833d553bda62a8bd0befa85e3f3bcd4123126bb9f835b3c2d82debe
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
//! E2e tests for category: post_processor_management

use kreuzberg::{clear_post_processors, list_post_processors};

#[test]
fn test_post_processors_clear() {
    // Clear all post-processors and verify list is empty
    let _ = clear_post_processors();
}

#[test]
fn test_post_processors_list() {
    // List all registered post-processors
    let _ = list_post_processors();
}
