// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:c1dfa38f25cb4a4f3ae999d5f20b3224282c944b5460083a05218399c26fa935
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
//! E2e tests for category: reranker_backend_management

use xberg::{clear_reranker_backends, list_reranker_backends};

#[test]
fn test_clear_reranker_backends() {
    // Clear all reranker backends and verify list is empty
    let _ = clear_reranker_backends();
}

#[test]
fn test_list_reranker_backends() {
    // List all registered reranker backends
    let _ = list_reranker_backends();
}
