// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:3fa62918260859c2452369986e24fcd42afb1ea8eb520c36367bc0a473c3d195
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
//! E2e tests for category: tokenizer_backend_management

use xberg::{clear_tokenizer_backends, list_tokenizer_backends};

#[test]
fn test_tokenizer_backends_clear() {
    // Clear all tokenizer backends and verify list is empty
    let _ = clear_tokenizer_backends();
}

#[test]
fn test_tokenizer_backends_list() {
    // List all registered tokenizer backends
    let _ = list_tokenizer_backends();
}
