# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:356ed0ad572128a92e2a68ca531b92cd783973ff49e6e7f17fef8212f0216bcf
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.CacheStats do
  @moduledoc "Aggregate statistics for a xberg cache directory."

  @typedoc "Aggregate statistics for a xberg cache directory."
  @type t :: %__MODULE__{
  total_files: non_neg_integer(),
  total_size_mb: float(),
  available_space_mb: float(),
  oldest_file_age_days: float(),
  newest_file_age_days: float()
  }

  defstruct total_files: 0,
  total_size_mb: 0.0,
  available_space_mb: 0.0,
  oldest_file_age_days: 0.0,
  newest_file_age_days: 0.0
end
