# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:0ce3ea7bbabccafc622b4dd87ac0f00356dd0426ec66977c856525dabafdc585
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.CaptioningConfig do
  @moduledoc "Configuration for the VLM captioning post-processor."

  @typedoc "Configuration for the VLM captioning post-processor."
  @type t :: %__MODULE__{
  llm: Xberg.LlmConfig.t(),
  prompt: String.t() | nil,
  min_image_area: non_neg_integer()
  }

  defstruct llm: nil,
  prompt: nil,
  min_image_area: 0
end
