# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:0ce3ea7bbabccafc622b4dd87ac0f00356dd0426ec66977c856525dabafdc585
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.ContributorRole do
  @moduledoc "JATS contributor with role."

  @typedoc "JATS contributor with role."
  @type t :: %__MODULE__{
  name: String.t() | nil,
  role: String.t() | nil
  }

  defstruct name: nil,
  role: nil
end
