# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:0ce3ea7bbabccafc622b4dd87ac0f00356dd0426ec66977c856525dabafdc585
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.DjotLink do
  @moduledoc "Link element in Djot."

  @typedoc "Link element in Djot."
  @type t :: %__MODULE__{
  url: String.t() | nil,
  text: String.t() | nil,
  title: String.t() | nil
  }

  defstruct url: nil,
  text: nil,
  title: nil
end
