# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:3fa62918260859c2452369986e24fcd42afb1ea8eb520c36367bc0a473c3d195
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.DocumentRelationship do
  @moduledoc "A resolved relationship between two nodes in the document tree."

  @typedoc "A resolved relationship between two nodes in the document tree."
  @type t :: %__MODULE__{
  source: non_neg_integer(),
  target: non_neg_integer(),
  kind: String.t() | nil
  }

  defstruct source: 0,
  target: 0,
  kind: :footnote_reference
end
