# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:356ed0ad572128a92e2a68ca531b92cd783973ff49e6e7f17fef8212f0216bcf
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.DocxMetadata do
  @moduledoc """
  Word document metadata.

  Extracted from DOCX files using shared Office Open XML metadata extraction.
  Integrates with `office_metadata` module for core/app/custom properties.
  """

  @typedoc "Word document metadata."
  @type t :: %__MODULE__{
  core_properties: Xberg.CoreProperties.t() | nil,
  app_properties: Xberg.DocxAppProperties.t() | nil,
  custom_properties: map() | nil
  }

  defstruct core_properties: nil,
  app_properties: nil,
  custom_properties: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
    |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
