# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:356ed0ad572128a92e2a68ca531b92cd783973ff49e6e7f17fef8212f0216bcf
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.EmbeddedFile do
  @moduledoc "Embedded file descriptor extracted from the PDF name tree."

  @typedoc "Embedded file descriptor extracted from the PDF name tree."
  @type t :: %__MODULE__{
  name: String.t() | nil,
  data: binary(),
  compressed_size: non_neg_integer(),
  mime_type: String.t() | nil
  }

  defstruct name: nil,
  data: <<>>,
  compressed_size: 0,
  mime_type: nil
end
