# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:c1dfa38f25cb4a4f3ae999d5f20b3224282c944b5460083a05218399c26fa935
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.ExtractionMethod do
  @moduledoc "How the extracted text was produced."

  @typedoc "How the extracted text was produced."
  @type t :: :native | :ocr | :mixed

  @native :native
  @ocr :ocr
  @mixed :mixed

  @doc "Text extracted directly from the document's native format (no OCR)."
  @spec native() :: t()
  def native, do: @native
  @doc "All text was obtained via OCR (e.g. scanned image-only PDF)."
  @spec ocr() :: t()
  def ocr, do: @ocr
  @doc "Text came from a combination of native extraction and OCR."
  @spec mixed() :: t()
  def mixed, do: @mixed
end
