# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:c1dfa38f25cb4a4f3ae999d5f20b3224282c944b5460083a05218399c26fa935
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.ExtractInputKind do
  @moduledoc "Source kind for [`ExtractInput`]."

  @typedoc "Source kind for [`ExtractInput`]."
  @type t :: :bytes | :uri

  @bytes :bytes
  @uri :uri

  @doc "Raw in-memory bytes."
  @spec bytes() :: t()
  def bytes, do: @bytes
  @doc "A filesystem path, `file://` URI, or HTTP(S) URL."
  @spec uri() :: t()
  def uri, do: @uri
end
