# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:356ed0ad572128a92e2a68ca531b92cd783973ff49e6e7f17fef8212f0216bcf
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.ExtractInputKind do
  @moduledoc "Source kind for [`ExtractInput`]."

  @typedoc "Source kind for [`ExtractInput`]."
  @type t :: :bytes | :uri

  @bytes :bytes
  @uri :uri

  @doc "Raw in-memory bytes."
  @spec bytes() :: t()
  def bytes, do: @bytes
  @doc "A filesystem path, `file://` URI, or HTTP(S) URL."
  @spec uri() :: t()
  def uri, do: @uri
end
