# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:c1dfa38f25cb4a4f3ae999d5f20b3224282c944b5460083a05218399c26fa935
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.ExtractedUri do
  @moduledoc """
  A URI extracted from a document.

  Represents any link, reference, or resource pointer found during extraction.
  The `kind` field classifies the URI semantically, while `label` carries
  optional human-readable display text.
  """

  @typedoc "A URI extracted from a document."
  @type t :: %__MODULE__{
  url: String.t() | nil,
  label: String.t() | nil,
  page: non_neg_integer() | nil,
  kind: String.t() | nil
  }

  defstruct url: nil,
  label: nil,
  page: nil,
  kind: :hyperlink
end
