# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:38dce430f8d9bea3dcf8465197cc598552462cd7a5930cc5e7e769e1d0990c01
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.FootnoteDefinition do
  @moduledoc """
  A footnote definition from markdown text.

  Represents `[^label]: content` declarations (including multi-line continuations).
  """

  @typedoc "A footnote definition from markdown text."
  @type t :: %__MODULE__{
  label: String.t() | nil,
  content: String.t() | nil,
  offset: non_neg_integer()
  }

  defstruct label: nil,
  content: nil,
  offset: 0
end
