# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:356ed0ad572128a92e2a68ca531b92cd783973ff49e6e7f17fef8212f0216bcf
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.ImageType do
  @moduledoc "Image type classification."

  @typedoc "Image type classification."
  @type t :: :"data-uri" | :"inline-svg" | :external | :relative

  @data_uri :"data-uri"
  @inline_svg :"inline-svg"
  @external :external
  @relative :relative

  @doc "Data URI image"
  @spec data_uri() :: t()
  def data_uri, do: @data_uri
  @doc "Inline SVG"
  @spec inline_svg() :: t()
  def inline_svg, do: @inline_svg
  @doc "External image URL"
  @spec external() :: t()
  def external, do: @external
  @doc "Relative path image"
  @spec relative() :: t()
  def relative, do: @relative
end
