# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:356ed0ad572128a92e2a68ca531b92cd783973ff49e6e7f17fef8212f0216bcf
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.Keyword do
  @moduledoc "Extracted keyword with metadata."

  @typedoc "Extracted keyword with metadata."
  @type t :: %__MODULE__{
  text: String.t() | nil,
  score: float(),
  algorithm: String.t() | nil,
  positions: [non_neg_integer()] | nil
  }

  defstruct text: nil,
  score: 0.0,
  algorithm: :yake,
  positions: nil
end
