# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:10f69d3922c038c3f3397ab775fa7c70016151a1f97a547ab8ea739f743a5288
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.Keyword do
  @moduledoc "Extracted keyword with metadata."

  @typedoc "Extracted keyword with metadata."
  @type t :: %__MODULE__{
  text: String.t() | nil,
  score: float(),
  algorithm: String.t() | nil,
  positions: [non_neg_integer()] | nil
  }

  defstruct text: nil,
  score: 0.0,
  algorithm: :yake,
  positions: nil
end
