# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:10f69d3922c038c3f3397ab775fa7c70016151a1f97a547ab8ea739f743a5288
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.LanguageDetectionConfig do
  @moduledoc "Language detection configuration."

  @typedoc "Language detection configuration."
  @type t :: %__MODULE__{
  enabled: boolean(),
  min_confidence: float(),
  detect_multiple: boolean()
  }

  defstruct enabled: true,
  min_confidence: 0.8,
  detect_multiple: false

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
    |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
