# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:0ce3ea7bbabccafc622b4dd87ac0f00356dd0426ec66977c856525dabafdc585
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.PageClassification do
  @moduledoc "Classification result for a single page."

  @typedoc "Classification result for a single page."
  @type t :: %__MODULE__{
  page_number: non_neg_integer(),
  labels: [Xberg.ClassificationLabel.t()]
  }

  defstruct page_number: 0,
  labels: []
end
