# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:c1dfa38f25cb4a4f3ae999d5f20b3224282c944b5460083a05218399c26fa935
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.PresetSample do
  @moduledoc "Pointer to a sample input + its reference output bundled with the preset."

  @typedoc "Pointer to a sample input + its reference output bundled with the preset."
  @type t :: %__MODULE__{
  input_path: String.t() | nil,
  output_path: String.t() | nil
  }

  defstruct input_path: nil,
  output_path: nil
end
