# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:10f69d3922c038c3f3397ab775fa7c70016151a1f97a547ab8ea739f743a5288
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.SsrfPolicy do
  @moduledoc "SSRF policy configuration."

  @typedoc "SSRF policy configuration."
  @type t :: %__MODULE__{
  deny_private: boolean(),
  max_redirects: non_neg_integer()
  }

  defstruct deny_private: true,
  max_redirects: 5

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
    |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
