# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:3fa62918260859c2452369986e24fcd42afb1ea8eb520c36367bc0a473c3d195
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.SupportedFormat do
  @moduledoc """
  A supported document format entry.

  Represents a file extension and its corresponding MIME type that Xberg can process.
  """

  @typedoc "A supported document format entry."
  @type t :: %__MODULE__{
  extension: String.t() | nil,
  mime_type: String.t() | nil
  }

  defstruct extension: nil,
  mime_type: nil
end
