# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:38dce430f8d9bea3dcf8465197cc598552462cd7a5930cc5e7e769e1d0990c01
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.TableDiff do
  @moduledoc "Cell-level changes for a pair of tables that share the same index."

  @typedoc "Cell-level changes for a pair of tables that share the same index."
  @type t :: %__MODULE__{
  from_index: non_neg_integer(),
  to_index: non_neg_integer(),
  cell_changes: [Xberg.CellChange.t()]
  }

  defstruct from_index: 0,
  to_index: 0,
  cell_changes: []
end
