<?php
// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:79ff9006e30ee2fc8d75b8f0cf1475f7ea7948a768d15a8841dbc237f6f8d7ce
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef


declare(strict_types=1);

namespace Kreuzberg\E2e;

use PHPUnit\Framework\TestCase;
use Kreuzberg\Kreuzberg;use Kreuzberg\ExtractionConfig;
/** E2e tests for category: code. */
final class CodeTest extends TestCase
{

    /** Test language detection from shebang line via bytes input */
    public function test_code_shebang_detection(): void
    {        $result = Kreuzberg::extractFileSync("code/script.sh", "text/x-source-code", \Kreuzberg\ExtractionConfig::from_json('{}'));

            $this->assertEquals("text/x-source-code", trim($result->mimeType));
            $this->assertGreaterThanOrEqual(10, strlen($result->content));
            $this->assertStringContainsString("build", $result->content);
    $this->assertStringContainsString("clean", $result->content);

    }

}
