<?php
// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:f1d9a4f3e11a0fb3b3f5a7ba8a0c897768ad230c7d2c8dfef213c1421b13b9fe
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code


declare(strict_types=1);

namespace Kreuzberg\E2e;

use PHPUnit\Framework\TestCase;
use Kreuzberg\Kreuzberg;
use Kreuzberg\ExtractionConfig;

/** E2e tests for category: embed_async_pending. */
final class EmbedAsyncPendingTest extends TestCase
{

    /** embed_texts_async: empty text list */
    public function test_embed_texts_async_empty_input(): void
    {
        $config = \Kreuzberg\EmbeddingConfig::from_json(json_encode(["model" => ["name" => "balanced", "type" => "preset"]]));
        $result = Kreuzberg::embedTextsAsync([], $config);

        $this->assertCount(0, $result);

    }


    /** embed_texts_async: basic async embedding */
    public function test_embed_texts_async_happy(): void
    {
        $config = \Kreuzberg\EmbeddingConfig::from_json(json_encode(["model" => ["name" => "balanced", "type" => "preset"]]));
        $result = Kreuzberg::embedTextsAsync(["First", "Second"], $config);

        $this->assertGreaterThanOrEqual(2, count($result));

    }


    /** embed_texts_async: preset override */
    public function test_embed_texts_async_preset_switch(): void
    {
        $config = \Kreuzberg\EmbeddingConfig::from_json(json_encode(["model" => ["name" => "balanced", "type" => "preset"]]));
        $this->expectNotToPerformAssertions();
        $result = Kreuzberg::embedTextsAsync(["Text"], $config);


    }

}
