<?php
// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:f1d9a4f3e11a0fb3b3f5a7ba8a0c897768ad230c7d2c8dfef213c1421b13b9fe
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code


declare(strict_types=1);

namespace Kreuzberg\E2e;

use PHPUnit\Framework\TestCase;
use Kreuzberg\Kreuzberg;
use Kreuzberg\ExtractionConfig;

/** E2e tests for category: ocr_backend_management. */
final class OcrBackendManagementTest extends TestCase
{

    /** Clear all OCR backends and verify list is empty */
    public function test_ocr_backends_clear(): void
    {
        $this->expectNotToPerformAssertions();
        $result = Kreuzberg::clearOcrBackends();


    }


    /** List all registered OCR backends */
    public function test_ocr_backends_list(): void
    {
        $this->expectNotToPerformAssertions();
        $result = Kreuzberg::listOcrBackends();


    }


    /** Unregister nonexistent OCR backend gracefully */
    public function test_ocr_backends_unregister(): void
    {
        $this->expectNotToPerformAssertions();
        $result = Kreuzberg::unregisterOcrBackend("nonexistent-backend-xyz");


    }

}
