<?php
// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:65c81b783487ffa227bde3cbce25db912c1c454d597969afc02ea8924a5a781b
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code


declare(strict_types=1);

namespace Kreuzberg\E2e;

use PHPUnit\Framework\TestCase;
use Kreuzberg\Kreuzberg;
use Kreuzberg\ExtractionConfig;

/** E2e tests for category: registry_operations. */
final class RegistryOperationsTest extends TestCase
{

    /** Get file extensions for DOCX MIME type */
    public function test_extensions_docx(): void
    {
        $this->expectNotToPerformAssertions();
        $result = Kreuzberg::getExtensionsForMime("application/vnd.openxmlformats-officedocument.wordprocessingml.document");


    }


    /** Get file extensions for HTML MIME type */
    public function test_extensions_html(): void
    {
        $this->expectNotToPerformAssertions();
        $result = Kreuzberg::getExtensionsForMime("text/html");


    }


    /** Get file extensions for PDF MIME type */
    public function test_extensions_pdf(): void
    {
        $this->expectNotToPerformAssertions();
        $result = Kreuzberg::getExtensionsForMime("application/pdf");


    }

}
