<?php
// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:38dce430f8d9bea3dcf8465197cc598552462cd7a5930cc5e7e769e1d0990c01
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code


declare(strict_types=1);

namespace Xberg\E2e;

use PHPUnit\Framework\TestCase;
use Xberg\Xberg;
use Xberg\ExtractionConfig;

/** E2e tests for category: tokenizer_backend_management. */
final class TokenizerBackendManagementTest extends TestCase
{

    /** Clear all tokenizer backends and verify list is empty */
    public function test_tokenizer_backends_clear(): void
    {
        $this->expectNotToPerformAssertions();
        $result = Xberg::clearTokenizerBackends();


    }


    /** List all registered tokenizer backends */
    public function test_tokenizer_backends_list(): void
    {
        $this->expectNotToPerformAssertions();
        $result = Xberg::listTokenizerBackends();


    }

}
