// Generated by alef. Do not edit by hand.

package dev.kreuzberg

import java.nio.file.Path

/**
 * Batch item for file extraction.
 *
 * Used with `batch_extract_files` and `batch_extract_files_sync`
 * to represent a single file in a batch extraction job.
 */
data class BatchFileItem(
    val path: Path,
    val config: FileExtractionConfig?,
)
