// Generated by alef. Do not edit by hand.

package dev.kreuzberg

/**
 * CSV/TSV file metadata.
 */
data class CsvMetadata(
    val rowCount: Int,
    val columnCount: Int,
    val delimiter: String?,
    val hasHeader: Boolean,
    val columnTypes: List<String>?,
)
