// Generated by alef. Do not edit by hand.

package dev.kreuzberg

/**
 * Top-level structured document representation.
 *
 * A flat array of nodes with index-based parent/child references forming a tree.
 * Root-level nodes have `parent: None`. Use `body_roots()` and `furniture_roots()`
 * to iterate over top-level content by layer.
 *
 * # Validation
 *
 * Call `validate()` after construction to verify all node indices are in bounds
 * and parent-child relationships are bidirectionally consistent.
 */
data class DocumentStructure(
    val nodes: List<DocumentNode>,
    val sourceFormat: String?,
    val relationships: List<DocumentRelationship>,
    val nodeTypes: List<String>,
)
