// Generated by alef. Do not edit by hand.

package dev.kreuzberg

/**
 * Embedded file descriptor extracted from the PDF name tree.
 */
data class EmbeddedFile(
    val name: String,
    val data: ByteArray,
    val mimeType: String?,
)
