// Generated by alef. Do not edit by hand.

package dev.kreuzberg

/**
 * General extraction result used by the core extraction API.
 *
 * This is the main result type returned by all extraction functions.
 */
data class ExtractionResult(
    val content: String,
    val mimeType: String,
    val metadata: Metadata,
    val extractionMethod: ExtractionMethod?,
    val tables: List<Table>,
    val detectedLanguages: List<String>?,
    val chunks: List<Chunk>?,
    val images: List<ExtractedImage>?,
    val pages: List<PageContent>?,
    val elements: List<Element>?,
    val djotContent: DjotContent?,
    val ocrElements: List<OcrElement>?,
    val document: DocumentStructure?,
    val extractedKeywords: List<Keyword>?,
    val qualityScore: Double?,
    val processingWarnings: List<ProcessingWarning>,
    val annotations: List<PdfAnnotation>?,
    val children: List<ArchiveEntry>?,
    val uris: List<Uri>?,
    val structuredOutput: String?,
    val codeIntelligence: String?,
    val llmUsage: List<LlmUsage>?,
    val formattedContent: String?,
    val ocrInternalDocument: String?,
)
