// Generated by alef. Do not edit by hand.
// alef:hash:6a8400ffd6e27c557ffd585458e080034774f33340cc49f53c2cb322a0da85dd
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
    "NestedBlockDepth",
)

package dev.kreuzberg

/** FictionBook (FB2) metadata. */
data class FictionBookMetadata(
    /** Genre tags as declared in the FB2 `<genre>` elements. */
    val genres: List<String> = emptyList(),
    /** Book series (sequence) names, if any. */
    val sequences: List<String> = emptyList(),
    /** Short annotation / summary from the FB2 `<annotation>` element. */
    val annotation: String? = null,
)
