// Generated by alef. Do not edit by hand.

package dev.kreuzberg

/**
 * FictionBook (FB2) metadata.
 */
data class FictionBookMetadata(
    val genres: List<String>,
    val sequences: List<String>,
    val annotation: String?,
)
