// Generated by alef. Do not edit by hand.

package dev.kreuzberg

/**
 * Block-level element in a Djot document.
 *
 * Represents structural elements like headings, paragraphs, lists, code blocks, etc.
 */
data class FormattedBlock(
    val blockType: BlockType,
    val level: Long?,
    val inlineContent: List<InlineElement>,
    val attributes: String?,
    val language: String?,
    val code: String?,
    val children: List<FormattedBlock>,
)
