// Generated by alef. Do not edit by hand.

package dev.kreuzberg

/**
 * A text block with hierarchy level assignment.
 *
 * Represents a block of text with semantic heading information extracted from
 * font size clustering and hierarchical analysis.
 */
data class HierarchicalBlock(
    val text: String,
    val fontSize: Float,
    val level: String,
    val bbox: List<Float>?,
)
