// Generated by alef. Do not edit by hand.

package dev.kreuzberg

import java.nio.file.Path

/**
 * Configuration for styled HTML output.
 *
 * When set on `ExtractionConfig.html_output` alongside
 * `output_format = OutputFormat.Html`, the pipeline builds a
 * `StyledHtmlRenderer` instead of
 * the plain comrak-based renderer.
 */
data class HtmlOutputConfig(
    val css: String?,
    val cssFile: Path?,
    val theme: HtmlTheme,
    val classPrefix: String,
    val embedCss: Boolean,
)
