// Generated by alef. Do not edit by hand.

package dev.kreuzberg

/**
 * Types of inline elements in Djot.
 */
enum class InlineType {
    TEXT,
    STRONG,
    EMPHASIS,
    HIGHLIGHT,
    SUBSCRIPT,
    SUPERSCRIPT,
    INSERT,
    DELETE,
    CODE,
    LINK,
    IMAGE,
    SPAN,
    MATH,
    RAW_INLINE,
    FOOTNOTE_REF,
    SYMBOL,
}
