// Generated by alef. Do not edit by hand.

package dev.kreuzberg

/**
 * The 17 canonical document layout classes.
 *
 * All model backends (RT-DETR, YOLO, etc.) map their native class IDs
 * to this shared set. Models with fewer classes (DocLayNet: 11, PubLayNet: 5)
 * map to the closest equivalent.
 *
 * Wire format is snake_case in all serializers (JSON, TOML, YAML).
 */
enum class LayoutClass {
    CAPTION,
    FOOTNOTE,
    FORMULA,
    LIST_ITEM,
    PAGE_FOOTER,
    PAGE_HEADER,
    PICTURE,
    SECTION_HEADER,
    TABLE,
    TEXT,
    TITLE,
    DOCUMENT_INDEX,
    CODE,
    CHECKBOX_SELECTED,
    CHECKBOX_UNSELECTED,
    FORM,
    KEY_VALUE_REGION,
}
