// Generated by alef. Do not edit by hand.

package dev.kreuzberg

import java.nio.file.Path

/**
 * Combined paths to all models needed for OCR (backward compatibility).
 */
data class ModelPaths(
    val detModel: Path,
    val clsModel: Path,
    val recModel: Path,
    val dictFile: Path,
)
