// Generated by alef. Do not edit by hand.

package dev.kreuzberg

/**
 * Confidence scores for an OCR element.
 *
 * Separates detection confidence (how confident that text exists at this location)
 * from recognition confidence (how confident about the actual text content).
 */
data class OcrConfidence(
    val detection: Double?,
    val recognition: Double,
)
