// Generated by alef. Do not edit by hand.

package dev.kreuzberg

/**
 * Configuration for OCR element extraction.
 *
 * Controls how OCR elements are extracted and filtered.
 */
data class OcrElementConfig(
    val includeElements: Boolean,
    val minLevel: OcrElementLevel,
    val minConfidence: Double,
    val buildHierarchy: Boolean,
)
