// Generated by alef. Do not edit by hand.

package dev.kreuzberg

/**
 * Quality thresholds for OCR fallback decisions and pipeline quality gating.
 *
 * All fields default to the values that match the previous hardcoded behavior,
 * so `OcrQualityThresholds.default()` preserves existing semantics exactly.
 */
data class OcrQualityThresholds(
    val minTotalNonWhitespace: Long,
    val minNonWhitespacePerPage: Double,
    val minMeaningfulWordLen: Long,
    val minMeaningfulWords: Long,
    val minAlnumRatio: Double,
    val minGarbageChars: Long,
    val maxFragmentedWordRatio: Double,
    val criticalFragmentedWordRatio: Double,
    val minAvgWordLength: Double,
    val minWordsForAvgLengthCheck: Long,
    val minConsecutiveRepeatRatio: Double,
    val minWordsForRepeatCheck: Long,
    val substantiveMinChars: Long,
    val nonTextMinChars: Long,
    val alnumWsRatioThreshold: Double,
    val pipelineMinQuality: Double,
)
