// Generated by alef. Do not edit by hand.

package dev.kreuzberg

/**
 * PDF-specific metadata.
 *
 * Contains metadata fields specific to PDF documents that are not in the common
 * `Metadata` structure. Common fields like title, authors, keywords, and dates
 * are at the `Metadata` level.
 */
data class PdfMetadata(
    val pdfVersion: String?,
    val producer: String?,
    val isEncrypted: Boolean?,
    val width: Long?,
    val height: Long?,
    val pageCount: Int?,
)
