// Generated by alef. Do not edit by hand.

package dev.kreuzberg

/**
 * Post-processor configuration.
 */
data class PostProcessorConfig(
    val enabled: Boolean,
    val enabledProcessors: List<String>?,
    val disabledProcessors: List<String>?,
    val enabledSet: String?,
    val disabledSet: String?,
)
