// Generated by alef. Do not edit by hand.
// alef:hash:65c81b783487ffa227bde3cbce25db912c1c454d597969afc02ea8924a5a781b
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
)

package dev.kreuzberg

/** Post-processor configuration. */
data class PostProcessorConfig(
    /** Enable post-processors */
    val enabled: Boolean = true,
    /** Whitelist of processor names to run (None = all enabled) */
    val enabledProcessors: List<String>? = null,
    /** Blacklist of processor names to skip (None = none disabled) */
    val disabledProcessors: List<String>? = null,
    /** Pre-computed AHashSet for O(1) enabled processor lookup */
    val enabledSet: List<String>? = null,
    /** Pre-computed AHashSet for O(1) disabled processor lookup */
    val disabledSet: List<String>? = null,
)
