// Generated by alef. Do not edit by hand.

package dev.kreuzberg

/**
 * Token reduction configuration.
 */
data class TokenReductionOptions(
    val mode: String,
    val preserveImportantWords: Boolean,
)
