// Generated by alef. Do not edit by hand.

package dev.kreuzberg

/**
 * XML metadata extracted during XML parsing.
 *
 * Provides statistics about XML document structure.
 */
data class XmlMetadata(
    val elementCount: Int,
    val uniqueElements: List<String>,
)
