// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:40aa68897f9927329a5a10cb8aa2c39f7c2d2fa54a5679bea6626db807a4830e
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
import XCTest
import Foundation
import Kreuzberg
import RustBridge

/// E2e tests for category: async.
final class AsyncTests: XCTestCase {
    override class func setUp() {
        super.setUp()
        let _testDocs = URL(fileURLWithPath: #filePath)
            .deletingLastPathComponent() // <Module>Tests/
            .deletingLastPathComponent() // Tests/
            .deletingLastPathComponent() // swift/
            .deletingLastPathComponent() // packages/
            .deletingLastPathComponent() // <repo root>
            .appendingPathComponent("test_documents")
        if FileManager.default.fileExists(atPath: _testDocs.path) {
            FileManager.default.changeCurrentDirectoryPath(_testDocs.path)
        }
    }

    func testAsyncExtractBytesEmptyMime() async throws {
        // extract_bytes empty MIME async
        do {
            let contentData = try Data(contentsOf: URL(fileURLWithPath: "text/plain.txt"))
            let contentVec = RustVec<UInt8>()
            for _byte in contentData { contentVec.push(value: _byte) }
            let configObj = try extractionConfigFromJson("{}")
            _ = try await extractBytes(contentVec, "", configObj)
            XCTFail("expected to throw")
        } catch {
            // success
        }
    }

    func testAsyncExtractBytesInvalidMime() async throws {
        // extract_bytes unsupported MIME async
        do {
            let contentData = try Data(contentsOf: URL(fileURLWithPath: "text/plain.txt"))
            let contentVec = RustVec<UInt8>()
            for _byte in contentData { contentVec.push(value: _byte) }
            let configObj = try extractionConfigFromJson("{}")
            _ = try await extractBytes(contentVec, "application/x-nonexistent", configObj)
            XCTFail("expected to throw")
        } catch {
            // success
        }
    }

}
