// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:d232fc2b65929575e2e44b5c884c3c03925f1687bb281fe1078bcc6e8bcc71df
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
// swift-format-ignore-file

import XCTest
import Foundation
import Kreuzberg
import RustBridge

/// E2e tests for category: code.
final class CodeTests: XCTestCase {
    override class func setUp() {
        super.setUp()
        let _testDocs = URL(fileURLWithPath: #filePath)
            .deletingLastPathComponent() // <Module>Tests/
            .deletingLastPathComponent() // Tests/
            .deletingLastPathComponent() // swift/
            .deletingLastPathComponent() // packages/
            .deletingLastPathComponent() // <repo root>
            .appendingPathComponent("test_documents")
        if FileManager.default.fileExists(atPath: _testDocs.path) {
            FileManager.default.changeCurrentDirectoryPath(_testDocs.path)
        }
    }

    func testCodeShebangDetection() throws {
        // Test language detection from shebang line via bytes input
        let result = try Kreuzberg.extractFileSync("code/script.sh", "text/x-source-code", "{}")
        XCTAssertEqual(result.mimeType.trimmingCharacters(in: CharacterSet.whitespacesAndNewlines), "text/x-source-code")
        XCTAssertGreaterThanOrEqual(result.content.count, 10)
        XCTAssertTrue(result.content.contains("build"), "expected to contain: \("build")")
        XCTAssertTrue(result.content.contains("clean"), "expected to contain: \("clean")")
    }

}
