// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:4df4aa4562e30a64ad9210fea81ee0a1f6c29874b3ca8147bd91e63c31cfcb70
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
// swift-format-ignore-file

import XCTest
import Foundation
import Kreuzberg
import RustBridge

/// E2e tests for category: registry_operations.
final class RegistryOperationsTests: XCTestCase {
    func testExtensionsDocx() throws {
        // Get file extensions for DOCX MIME type
        let result = try Kreuzberg.getExtensionsForMime(mimeType: "application/vnd.openxmlformats-officedocument.wordprocessingml.document")
    }

    func testExtensionsHtml() throws {
        // Get file extensions for HTML MIME type
        let result = try Kreuzberg.getExtensionsForMime(mimeType: "text/html")
    }

    func testExtensionsPdf() throws {
        // Get file extensions for PDF MIME type
        let result = try Kreuzberg.getExtensionsForMime(mimeType: "application/pdf")
    }

}
