// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:b0d91fb62af08d6df7113b91209e9869bee112506d29e5da63e938bfffebaadf
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/sample_crate-dev/alef
// swift-format-ignore-file

import XCTest
import Foundation
#if canImport(FoundationNetworking)
import FoundationNetworking
#endif
import Kreuzberg
import RustBridge

/// E2e tests for category: validator_management.
final class ValidatorManagementTests: XCTestCase {
    func testValidatorsClear() throws {
        // Clear all validators and verify list is empty
        let result = try Kreuzberg.clearValidators()
    }

    func testValidatorsList() throws {
        // List all registered validators
        let result = try Kreuzberg.listValidators()
    }

}
