// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:a00e0c73bb14fd057880bb677909683621ddc9ea8082adb69a8ef52b2676cdf4
#nullable enable

using System;

namespace Kreuzberg;

public class CacheException : KreuzbergErrorException
{
    public CacheException(string message) : base(message) { }

    public CacheException(string message, Exception innerException) : base(message, innerException) { }
}
