// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:65c81b783487ffa227bde3cbce25db912c1c454d597969afc02ea8924a5a781b
#nullable enable

using System;

namespace Kreuzberg;

/// <summary>
/// A cache read or write operation failed.
/// </summary>
public class CacheException : KreuzbergErrorException
{
    public CacheException(string message) : base(message) { }

    public CacheException(string message, Exception innerException) : base(message, innerException) { }
}
