// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:b737930e14166c66cb9ac908419d97162ae293bbb908c61f175030e14be45188
#nullable enable

using System;

namespace Kreuzberg;

public class CancelledException : KreuzbergErrorException
{
    public CancelledException(string message) : base(message) { }

    public CancelledException(string message, Exception innerException) : base(message, innerException) { }
}
