// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:65117d288912e7df5e977f99f2d09efab54c6797514ab3e309dac9b711595575
#nullable enable

using System;

namespace Kreuzberg;

/// <summary>
/// The extraction was cancelled via a `CancellationToken`.
/// </summary>
public class CancelledException : KreuzbergErrorException
{
    public CancelledException(string message) : base(message) { }

    public CancelledException(string message, Exception innerException) : base(message, innerException) { }
}
