// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:65c81b783487ffa227bde3cbce25db912c1c454d597969afc02ea8924a5a781b
#nullable enable

using System;

namespace Kreuzberg;

/// <summary>
/// The extraction was cancelled via a `CancellationToken`.
/// </summary>
public class CancelledException : KreuzbergErrorException
{
    public CancelledException(string message) : base(message) { }

    public CancelledException(string message, Exception innerException) : base(message, innerException) { }
}
