// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:76413394a839d33af186df184283ea5b32ac41c8eb167a2f95e9bf0e4c889834
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// Chunk response with chunks and metadata.
/// </summary>
public sealed record ChunkResponse
{
    /// <summary>
    /// List of chunks
    /// </summary>
    [JsonPropertyName("chunks")]
    public List<string> Chunks { get; init; } = [];

    /// <summary>
    /// Total number of chunks
    /// </summary>
    [JsonPropertyName("chunk_count")]
    public ulong ChunkCount { get; init; } = 0;

    /// <summary>
    /// Configuration used for chunking
    /// </summary>
    [JsonPropertyName("config")]
    public required string Config { get; init; }

    /// <summary>
    /// Input text size in bytes
    /// </summary>
    [JsonPropertyName("input_size_bytes")]
    public ulong InputSizeBytes { get; init; } = 0;

    /// <summary>
    /// Chunker type used for chunking
    /// </summary>
    [JsonPropertyName("chunker_type")]
    public required string ChunkerType { get; init; }


    /// <summary>
    /// Parse a <see cref="ChunkResponse"/> from a JSON string.
    /// </summary>
    /// <exception cref="KreuzbergException">When the JSON cannot be deserialised.</exception>
    public static ChunkResponse FromJson(string json)
    {
        try
        {
            return JsonSerializer.Deserialize<ChunkResponse>(json, JsonOptions)
                ?? throw new KreuzbergException($"Failed to parse ChunkResponse from JSON: deserializer returned null");
        }
        catch (KreuzbergException)
        {
            throw;
        }
        catch (Exception e)
        {
            throw new KreuzbergException($"Failed to parse ChunkResponse from JSON: {e.Message}", e);
        }
    }

    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault,
        Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) },
    };
}
