// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:e96e88b028ee650f7fa1df17d62630a20044cb98a78bfac698fceaa11d3c20a9
#nullable enable

using System;

namespace Kreuzberg;

/// <summary>
/// The embedding model or embedding pipeline returned an error.
/// </summary>
public class EmbeddingException : KreuzbergErrorException
{
    public EmbeddingException(string message) : base(message) { }

    public EmbeddingException(string message, Exception innerException) : base(message, innerException) { }
}
