// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:7aa688f1ac19daa9d8c762edb112dde6dc707533649ff06785f50add31bd8e2f
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// Request parameters for LLM-based structured extraction.
/// </summary>
public sealed record ExtractStructuredParams
{
    /// <summary>
    /// File path to extract from
    /// </summary>
    [JsonPropertyName("path")]
    public required string Path { get; init; }

    /// <summary>
    /// JSON schema for structured output
    /// </summary>
    [JsonPropertyName("schema")]
    public required object Schema { get; init; }

    /// <summary>
    /// LLM model (e.g., "openai/gpt-4o")
    /// </summary>
    [JsonPropertyName("model")]
    public required string Model { get; init; }

    /// <summary>
    /// Schema name (default: "extraction")
    /// </summary>
    [JsonPropertyName("schema_name")]
    public required string SchemaName { get; init; }

    /// <summary>
    /// Schema description for the LLM
    /// </summary>
    [JsonPropertyName("schema_description")]
    public string? SchemaDescription { get; init; } = null;

    /// <summary>
    /// Custom Jinja2 prompt template
    /// </summary>
    [JsonPropertyName("prompt")]
    public string? Prompt { get; init; } = null;

    /// <summary>
    /// API key (optional, falls back to env)
    /// </summary>
    [JsonPropertyName("api_key")]
    public string? ApiKey { get; init; } = null;

    /// <summary>
    /// Enable strict mode
    /// </summary>
    [JsonPropertyName("strict")]
    public bool Strict { get; init; } = false;


    /// <summary>
    /// Parse a <see cref="ExtractStructuredParams"/> from a JSON string.
    /// </summary>
    /// <exception cref="KreuzbergException">When the JSON cannot be deserialised.</exception>
    public static ExtractStructuredParams FromJson(string json)
    {
        try
        {
            return JsonSerializer.Deserialize<ExtractStructuredParams>(json, JsonOptions)
                ?? throw new KreuzbergException($"Failed to parse ExtractStructuredParams from JSON: deserializer returned null");
        }
        catch (KreuzbergException)
        {
            throw;
        }
        catch (Exception e)
        {
            throw new KreuzbergException($"Failed to parse ExtractStructuredParams from JSON: {e.Message}", e);
        }
    }

    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault,
        Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) },
    };
}
