// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:df8152500e027c9397b4635d4a0237af4723e23436ca39350515026d14123b7d
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;
/// <summary>
/// How the extracted text was produced.
/// </summary>
[JsonConverter(typeof(JsonStringEnumConverter))]
public enum ExtractionMethod
{
    [JsonPropertyName("native")]
    Native, [JsonPropertyName("ocr")]
    Ocr, [JsonPropertyName("mixed")]
    Mixed,
}
