// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:a0b798ccafa05000e6286c166081926a83798bf2e2760fa4323216d499acc103
#nullable enable

using System;

namespace Kreuzberg;

public class ImageProcessingException : KreuzbergErrorException
{
    public ImageProcessingException(string message) : base(message) { }

    public ImageProcessingException(string message, Exception innerException) : base(message, innerException) { }
}
