// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:ce4e87a1f12370d1809b226dfec517e209c1df55b81bc62758c9e6d88c17233a
#nullable enable

using System;

namespace Kreuzberg;

public class IoException : KreuzbergErrorException
{
    public IoException(string message) : base(message) { }

    public IoException(string message, Exception innerException) : base(message, innerException) { }
}
