// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:932c299e263134c4cc188f80ca1d81c1eca95f4378df129af6ff63176a4ee7ed
#nullable enable

using System;

namespace Kreuzberg;

public class IoException : KreuzbergErrorException
{
    public IoException(string message) : base(message) { }

    public IoException(string message, Exception innerException) : base(message, innerException) { }
}
