// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:65c81b783487ffa227bde3cbce25db912c1c454d597969afc02ea8924a5a781b
#nullable enable

using System;

namespace Kreuzberg;

public class KreuzbergException : Exception
{
    public int Code { get; }

    public KreuzbergException(int code, string message) : base(message)
    {
        Code = code;
    }

    public KreuzbergException(string message) : base(message)
    {
        Code = 0;
    }

    public KreuzbergException(string message, Exception innerException) : base(message, innerException)
    {
        Code = 0;
    }
}
