// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:740c5012904701fee6acaa339c14e09b8d6aabec4913ba82b7a4ce9124721264
#nullable enable

using System;

namespace Kreuzberg;

public class KreuzbergException : Exception
{
    public int Code { get; }

    public KreuzbergException(int code, string message) : base(message)
    {
        Code = code;
    }

    public KreuzbergException(string message) : base(message)
    {
        Code = 0;
    }

    public KreuzbergException(string message, Exception innerException) : base(message, innerException)
    {
        Code = 0;
    }
}
