// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:95240e08e70afb97a2049e262577fc554de4c9f1b1a1d36192d78117c24d87e9
#nullable enable

using System;

namespace Kreuzberg;

public class KreuzbergException : Exception
{
    public int Code { get; }

    public KreuzbergException(int code, string message) : base(message)
    {
        Code = code;
    }

    public KreuzbergException(string message) : base(message)
    {
        Code = 0;
    }

    public KreuzbergException(string message, Exception innerException) : base(message, innerException)
    {
        Code = 0;
    }
}
