// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:624015b4d2adcbb3241ab1066441042fc5f9e408161229b682c5ac566c281232
#nullable enable

using System;

namespace Kreuzberg;

public class OcrException : KreuzbergErrorException
{
    public OcrException(string message) : base(message) { }

    public OcrException(string message, Exception innerException) : base(message, innerException) { }
}
