// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:11830441715fabb85313457bbb8a12bb8c9f9cb673b1d4a0edf22ea18161006e
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;
/// <summary>
/// Type of paginated unit in a document.
///
/// Distinguishes between different types of "pages" (PDF pages, presentation slides, spreadsheet sheets).
/// </summary>
[JsonConverter(typeof(JsonStringEnumConverter))]
public enum PageUnitType
{    /// <summary>
     /// Standard document pages (PDF, DOCX, images)
     /// </summary>
    [JsonPropertyName("page")]
    Page,    /// <summary>
             /// Presentation slides (PPTX, ODP)
             /// </summary>
    [JsonPropertyName("slide")]
    Slide,    /// <summary>
              /// Spreadsheet sheets (XLSX, ODS)
              /// </summary>
    [JsonPropertyName("sheet")]
    Sheet,
}
