// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:3bd73c1f59a7c392684f750ee25bfc7da89e9e53bc34f993967faac903cbdc32
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;
/// <summary>/// Type of PDF annotation./// </summary>
[JsonConverter(typeof(JsonStringEnumConverter))]
public enum PdfAnnotationType
{/// <summary>    /// Sticky note / text annotation    /// </summary>
[JsonPropertyName("text")]
    Text,/// <summary>    /// Highlighted text region    /// </summary>
[JsonPropertyName("highlight")]
    Highlight,/// <summary>    /// Hyperlink annotation    /// </summary>
[JsonPropertyName("link")]
    Link,/// <summary>    /// Rubber stamp annotation    /// </summary>
[JsonPropertyName("stamp")]
    Stamp,/// <summary>    /// Underline text markup    /// </summary>
[JsonPropertyName("underline")]
    Underline,/// <summary>    /// Strikeout text markup    /// </summary>
[JsonPropertyName("strike_out")]
    StrikeOut,/// <summary>    /// Any other annotation type    /// </summary>
[JsonPropertyName("other")]
    Other,}
