// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:efd2140ced6a009a9d1d38ddc72b4db276a858d7af7ae2532a69917fe8e14cdc
#nullable enable

using System;

namespace Kreuzberg;

/// <summary>
/// PDF analysis step failed (only when `heuristics-pdf` feature is active).
/// </summary>
public class PdfAnalysisErrorException : HeuristicsErrorException
{
    public PdfAnalysisErrorException(string message) : base(message) { }

    public PdfAnalysisErrorException(string message, Exception innerException) : base(message, innerException) { }
}
