// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:fb6ee3a26a4b84cb6ac461d29a4bf1968b35151b917d02bfa86c40b50698a541
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;
/// <summary>
/// Page Segmentation Mode for Tesseract OCR
/// </summary>
[JsonConverter(typeof(JsonStringEnumConverter))]
public enum PsmMode
{
    [JsonPropertyName("osdonly")]
    OsdOnly, [JsonPropertyName("autoosd")]
    AutoOsd, [JsonPropertyName("autoonly")]
    AutoOnly, [JsonPropertyName("auto")]
    Auto, [JsonPropertyName("singlecolumn")]
    SingleColumn, [JsonPropertyName("singleblockvertical")]
    SingleBlockVertical, [JsonPropertyName("singleblock")]
    SingleBlock, [JsonPropertyName("singleline")]
    SingleLine, [JsonPropertyName("singleword")]
    SingleWord, [JsonPropertyName("circleword")]
    CircleWord, [JsonPropertyName("singlechar")]
    SingleChar,
}
