// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:4fdde9d9b5c1a730fa75e6a176ad1d0b930613975228f309d2cba632b92cb26b
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;
/// <summary>/// Result-shape selection for extraction results./// /// Distinct from `OutputFormat` (which controls rendering — Plain, Markdown,/// HTML, etc.). `ResultFormat` controls the *shape* of the result: a unified content/// blob vs. an element-based decomposition./// </summary>
[JsonConverter(typeof(JsonStringEnumConverter))]
public enum ResultFormat
{    /// <summary>    /// Unified format with all content in `content` field    /// </summary>
    [JsonPropertyName("unified")]
    Unified,    /// <summary>    /// Element-based format with semantic element extraction    /// </summary>
    [JsonPropertyName("element_based")]
    ElementBased,}
