// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:efd2140ced6a009a9d1d38ddc72b4db276a858d7af7ae2532a69917fe8e14cdc
#nullable enable

using System;

namespace Kreuzberg;

/// <summary>
/// The file parses as JSON but does not validate against the meta-schema.
/// </summary>
public class SchemaValidationException : LoadErrorException
{
    public SchemaValidationException(string message) : base(message) { }

    public SchemaValidationException(string message, Exception innerException) : base(message, innerException) { }
}
