// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:129f6c78bc96b39658ce61eefcba84c48dda7c11a0dc9f36687849db17ea4295
#nullable enable

using System;

namespace Kreuzberg;

/// <summary>
/// A security policy was violated (e.g. zip bomb, oversized archive).
/// </summary>
public class SecurityException : KreuzbergErrorException
{
    public SecurityException(string message) : base(message) { }

    public SecurityException(string message, Exception innerException) : base(message, innerException) { }
}
