// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:e96e88b028ee650f7fa1df17d62630a20044cb98a78bfac698fceaa11d3c20a9
#nullable enable

using System;

namespace Kreuzberg;

/// <summary>
/// JSON or MessagePack serialization/deserialization failed.
/// </summary>
public class SerializationException : KreuzbergErrorException
{
    public SerializationException(string message) : base(message) { }

    public SerializationException(string message, Exception innerException) : base(message, innerException) { }
}
