// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:19cfad6504d6b05279b0bed998155d14da8d1a1ae3f2389c214460b0738ef5b5
#nullable enable

using System;

namespace Kreuzberg;

public class SerializationException : KreuzbergErrorException
{
    public SerializationException(string message) : base(message) { }

    public SerializationException(string message, Exception innerException) : base(message, innerException) { }
}
