// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:6a863205e7a486a4e1b97dac288554ebbf65a8b3ad1aaa6799965109e6543cd4
#nullable enable

using System;

namespace Kreuzberg;

/// <summary>
/// Audio/video transcription failed.
/// </summary>
public class TranscriptionException : KreuzbergErrorException
{
    public TranscriptionException(string message) : base(message) { }

    public TranscriptionException(string message, Exception innerException) : base(message, innerException) { }
}
