// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:dba7c8b7d585c720af96ac48f5eea4377a92585398698f5565375a742e0a76ea
#nullable enable

using System;

namespace Kreuzberg;

public class UnsupportedFormatException : KreuzbergErrorException
{
    public UnsupportedFormatException(string message) : base(message) { }

    public UnsupportedFormatException(string message, Exception innerException) : base(message, innerException) { }
}
