// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:38dce430f8d9bea3dcf8465197cc598552462cd7a5930cc5e7e769e1d0990c01
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// swift-format-ignore-file

import XCTest
import Foundation
#if canImport(FoundationNetworking)
import FoundationNetworking
#endif
import Xberg
import RustBridge

/// E2e tests for category: renderer_management.
final class RendererManagementTests: XCTestCase {
    override class func setUp() {
        super.setUp()
        _ = "true".withCString { val in
            "CRAWLBERG_ALLOW_PRIVATE_NETWORK".withCString { key in
                setenv(key, val, 0)
            }
        }
    }

    func testRenderersClear() throws {
        // Clear all renderers and verify list is empty
        try Xberg.clearRenderers()
        // skipped: void-returning function has no result to assert on
    }

    func testRenderersList() throws {
        // List all registered renderers
        _ = try Xberg.listRenderers()
    }

}
