// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:4605dc5fbbc7fae10093d0e345afdfb6c29df2fa95c94d6856a9be0c4c18d6e9
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
import { defineConfig } from "vitest/config";
import wasm from "vite-plugin-wasm";

export default defineConfig({
  plugins: [wasm()],
  test: {
    include: ["tests/**/*.test.ts"],
    testTimeout: 30000,
    setupFiles: ["./setup.ts"],
  },
});
