// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:7812a20b06cb97d394236c3d88d3fd6de6b99e69b68bfc85e7ef407f89d26e84
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
import XCTest
import Foundation
import Kreuzberg
import RustBridge

/// E2e tests for category: registry_operations.
final class RegistryOperationsTests: XCTestCase {
    func testExtensionsDocx() throws {
        // Get file extensions for DOCX MIME type
        let result = try getExtensionsForMime("application/vnd.openxmlformats-officedocument.wordprocessingml.document")
    }

    func testExtensionsHtml() throws {
        // Get file extensions for HTML MIME type
        let result = try getExtensionsForMime("text/html")
    }

    func testExtensionsPdf() throws {
        // Get file extensions for PDF MIME type
        let result = try getExtensionsForMime("application/pdf")
        XCTAssertTrue(result.map { $0.as_str().toString() }.contains("pdf"), "expected to contain: \("pdf")")
    }

}
