/**
 * Generated by alef. Do not edit by hand.
 * alef:hash:6a863205e7a486a4e1b97dac288554ebbf65a8b3ad1aaa6799965109e6543cd4
 *
 * TypeScript trait bridge for outbound plugin implementations.
 */

export interface EmbeddingBackendBridge {
  name(): string;
  version(): string;
  initialize(): Promise<void>;
  shutdown(): Promise<void>;
  dimensions(): string;
  embed?(texts: string): string;
}

export class EmbeddingBackendAdapter {
  constructor(private bridge: EmbeddingBackendBridge) {}

  async dimensions(): Promise<string> {
    try {
      const result = await this.bridge.dimensions();
      return JSON.stringify({ ok: result });
    } catch (e) {
      return JSON.stringify({ err: String(e) });
    }
  }

  async embed(texts: string): Promise<string> {
    try {
      const result = await this.bridge.embed(texts);
      return JSON.stringify({ ok: result });
    } catch (e) {
      return JSON.stringify({ err: String(e) });
    }
  }

}
