/**
 * Generated by alef. Do not edit by hand.
 * alef:hash:c9dc9b974833d553bda62a8bd0befa85e3f3bcd4123126bb9f835b3c2d82debe
 *
 * TypeScript trait bridge for outbound plugin implementations.
 */

export interface RendererBridge {
  name(): string;
  version(): string;
  initialize(): Promise<void>;
  shutdown(): Promise<void>;
  render?(doc: string): string;
}

export class RendererAdapter {
  constructor(private bridge: RendererBridge) {}

  async render(doc: string): Promise<string> {
    try {
      const result = await this.bridge.render(doc);
      return JSON.stringify({ ok: result });
    } catch (e) {
      return JSON.stringify({ err: String(e) });
    }
  }

}
