/**
 * Generated by alef. Do not edit by hand.
 * alef:hash:f1d9a4f3e11a0fb3b3f5a7ba8a0c897768ad230c7d2c8dfef213c1421b13b9fe
 *
 * TypeScript trait bridge for outbound plugin implementations.
 */

export interface RerankerBackendBridge {
  name(): string;
  version(): string;
  initialize(): Promise<void>;
  shutdown(): Promise<void>;
  rerank?(query: string, documents: string): string;
}

export class RerankerBackendAdapter {
  constructor(private bridge: RerankerBackendBridge) {}

  async rerank(query: string, documents: string): Promise<string> {
    try {
      const result = await this.bridge.rerank(query, documents);
      return JSON.stringify({ ok: result });
    } catch (e) {
      return JSON.stringify({ err: String(e) });
    }
  }

}
