/**
 * Generated by alef. Do not edit by hand.
 * alef:hash:fc80bf10cd9e5e7f08a9c541fcd6220d7342df63fa1e17d6ecf17827e285a57b
 *
 * TypeScript trait bridge for outbound plugin implementations.
 */

export interface ValidatorBridge {
  name(): string;
  version(): string;
  initialize(): Promise<void>;
  shutdown(): Promise<void>;
  validate?(result: string, config: string): string;
  shouldValidate(result: string, config: string): string;
  priority(): string;
}

export class ValidatorAdapter {
  constructor(private bridge: ValidatorBridge) {}

  async validate(result: string, config: string): Promise<string> {
    try {
      const result = await this.bridge.validate(result, config);
      return JSON.stringify({ ok: result });
    } catch (e) {
      return JSON.stringify({ err: String(e) });
    }
  }

  async shouldValidate(result: string, config: string): Promise<string> {
    try {
      const result = await this.bridge.shouldValidate(result, config);
      return JSON.stringify({ ok: result });
    } catch (e) {
      return JSON.stringify({ err: String(e) });
    }
  }

  async priority(): Promise<string> {
    try {
      const result = await this.bridge.priority();
      return JSON.stringify({ ok: result });
    } catch (e) {
      return JSON.stringify({ err: String(e) });
    }
  }

}
