# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:b0d91fb62af08d6df7113b91209e9869bee112506d29e5da63e938bfffebaadf
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/sample_crate-dev/alef
# E2e tests for category: validator_management

test_that("validators_clear: Clear all validators and verify list is empty", {
  invisible(clear_validators())
  expect_true(TRUE)
})

test_that("validators_list: List all registered validators", {
  result <- list_validators()
  expect_true(TRUE)
})
