# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:6a863205e7a486a4e1b97dac288554ebbf65a8b3ad1aaa6799965109e6543cd4
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# E2e tests for category: rerank_async_pending

test_that("async_rerank: rerank_async: plugin model with no backend registered returns an error", {
  expect_error(rerank_async(query = "neural networks", documents = c("Neural networks are a class of machine learning models inspired by biological brains.", "The Eiffel Tower is located in Paris.", "Convolutional neural networks excel at image recognition tasks."), config = RerankerConfig$from_json(jsonlite::toJSON(list("model" = list("name" = "async_rerank", "type" = "plugin")), auto_unbox = TRUE))))
})
