# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:1ea2e31be2ea3875c4ac7b04e7c0c6025863bc99d4f62123c28991d3b085a679
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# E2e tests for category: embed_extra

test_that("embed_texts_batch: Batch embed texts", {
  result <- embed_texts_async(texts = c("Hello", "World"), config = EmbeddingConfig$from_json(jsonlite::toJSON(list("model" = list("name" = "balanced", "type" = "preset")), auto_unbox = TRUE)))
  expect_true(TRUE)
})
