# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:d8a72306fb931b82207473fb40ae0ee5f4f1e2c9d110e92abeb64939ecb556d7
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# E2e tests for category: embed_extra

test_that("embed_texts_batch: Batch embed texts", {
  result <- embed_texts(texts = c("Hello", "World"), config = EmbeddingConfig$from_json(jsonlite::toJSON(list("model" = list("name" = "balanced", "type" = "preset")), auto_unbox = TRUE)))
  expect_true(TRUE)
})
