# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:b0d91fb62af08d6df7113b91209e9869bee112506d29e5da63e938bfffebaadf
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/sample_crate-dev/alef
# E2e tests for category: document_extractor_management

test_that("document_extractors_clear: Clear all document extractors and verify list is empty", {
  invisible(clear_document_extractors())
  expect_true(TRUE)
})

test_that("extractors_list: List all registered document extractors", {
  result <- list_document_extractors()
  expect_true(TRUE)
})
