// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:3fa62918260859c2452369986e24fcd42afb1ea8eb520c36367bc0a473c3d195
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// The extraction was cancelled via a `CancellationToken`.
/// </summary>
public class CancelledException : XbergErrorException
{
    public CancelledException(string message) : base(message) { }

    public CancelledException(string message, Exception innerException) : base(message, innerException) { }
}
