// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:c1dfa38f25cb4a4f3ae999d5f20b3224282c944b5460083a05218399c26fa935
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// The preset's declared `id` does not match its file-system location.
/// </summary>
public class IdMismatchException : LoadErrorException
{
    public IdMismatchException(string message) : base(message) { }

    public IdMismatchException(string message, Exception innerException) : base(message, innerException) { }
}
