// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:356ed0ad572128a92e2a68ca531b92cd783973ff49e6e7f17fef8212f0216bcf
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// A file system or I/O operation failed. These errors always bubble up unchanged.
/// </summary>
public class IoException : XbergErrorException
{
    public IoException(string message) : base(message) { }

    public IoException(string message, Exception innerException) : base(message, innerException) { }
}
