// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:c1dfa38f25cb4a4f3ae999d5f20b3224282c944b5460083a05218399c26fa935
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// Errors produced while loading or validating a preset file.
/// </summary>
public class LoadErrorException : XbergException
{
    public LoadErrorException(string message) : base(message) { }

    public LoadErrorException(string message, Exception innerException) : base(message, innerException) { }
}
