// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:c1dfa38f25cb4a4f3ae999d5f20b3224282c944b5460083a05218399c26fa935
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// An internal `Mutex` or `RwLock` was found in a poisoned state.
/// </summary>
public class LockPoisonedException : XbergErrorException
{
    public LockPoisonedException(string message) : base(message) { }

    public LockPoisonedException(string message, Exception innerException) : base(message, innerException) { }
}
