// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:0ce3ea7bbabccafc622b4dd87ac0f00356dd0426ec66977c856525dabafdc585
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// The file is not valid JSON.
/// </summary>
public class ParseException : LoadErrorException
{
    public ParseException(string message) : base(message) { }

    public ParseException(string message, Exception innerException) : base(message, innerException) { }
}
