// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:38dce430f8d9bea3dcf8465197cc598552462cd7a5930cc5e7e769e1d0990c01
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// A registered plugin returned an error during extraction.
/// </summary>
public class PluginException : XbergErrorException
{
    public PluginException(string message) : base(message) { }

    public PluginException(string message, Exception innerException) : base(message, innerException) { }
}
