<?php

// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:cc2956f5955ac7e0f45e1cbf24d6d0be14416a6fe22ffe6a694316c85e480044
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
declare(strict_types=1);

namespace Kreuzberg;

/**
 * Per-category running counter for `RedactionStrategy.TokenReplace`.
 */
final class TokenCounter
{
    public static function new(): TokenCounter
    {
        throw new \RuntimeException('Not implemented — provided by the native extension.');
    }
}
