// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:9f578f2470bbec7549733c73ae6b7d724fd2f5f58441654ef1d408d21e501c7d
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code

package dev.kreuzberg.e2e;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import dev.kreuzberg.Kreuzberg;
import dev.kreuzberg.EmbeddingConfig;
import dev.kreuzberg.ExtractionConfig;
import java.util.Optional;
import dev.kreuzberg.JsonUtil;

/** E2e tests for category: embed_async_pending. */
public class EmbedAsyncPendingTest {

    @Test
    void testEmbedTextsAsyncEmptyInput() throws Exception {
        // embed_texts_async: empty text list
        var result = Kreuzberg.embedTextsAsync(java.util.List.of(), EmbeddingConfig.builder().build());
        // skipped: field 'embeddings' not available on result type

    }


    @Test
    void testEmbedTextsAsyncHappy() throws Exception {
        // embed_texts_async: basic async embedding
        var result = Kreuzberg.embedTextsAsync(java.util.Arrays.asList(JsonUtil.fromJson("\"First\"", String.class), JsonUtil.fromJson("\"Second\"", String.class)), EmbeddingConfig.builder().build());
        // skipped: field 'embeddings' not available on result type

    }


    @Test
    void testEmbedTextsAsyncPresetSwitch() throws Exception {
        // embed_texts_async: preset override
        var config = JsonUtil.fromJson("{\"model\":{\"name\":\"balanced\",\"type\":\"preset\"}}", EmbeddingConfig.class);

        var result = Kreuzberg.embedTextsAsync(java.util.Arrays.asList(JsonUtil.fromJson("\"Text\"", String.class)), config);


    }

}
