// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:efd2140ced6a009a9d1d38ddc72b4db276a858d7af7ae2532a69917fe8e14cdc
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code

package dev.kreuzberg.e2e;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import dev.kreuzberg.Kreuzberg;
import dev.kreuzberg.ExtractionConfig;
import java.util.Optional;
import dev.kreuzberg.JsonUtil;

/** E2e tests for category: reranker_backend_management. */
public class RerankerBackendManagementTest {

    @Test
    void testClearRerankerBackends() throws Exception {
        // Clear all reranker backends and verify list is empty
        Kreuzberg.clearRerankerBackends();


    }


    @Test
    void testListRerankerBackends() throws Exception {
        // List all registered reranker backends
        var result = Kreuzberg.listRerankerBackends();


    }

}
