# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:101f93f77893c2c7989723625cc5537a934c702f60a360b93d41055b40c41ceb
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
library(testthat)
devtools::load_all("../../packages/r")

testthat::set_max_fails(Inf)
.script_dir <- tryCatch(dirname(normalizePath(sys.frame(1)$ofile)), error = function(e) getwd())
test_dir(file.path(.script_dir, "tests"))
