# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:fc80bf10cd9e5e7f08a9c541fcd6220d7342df63fa1e17d6ecf17827e285a57b
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# frozen_string_literal: true

module Kreuzberg
  ## The version string for this package.
  VERSION = "5.0.0.pre.rc.18"
end
