// DO NOT EDIT - auto-generated by alef
// alef:hash:129f6c78bc96b39658ce61eefcba84c48dda7c11a0dc9f36687849db17ea4295
package dev.kreuzberg;

/**
 * A cache read or write operation failed.
 */
public class CacheException extends KreuzbergErrorException {
    /** Creates a new CacheException with the given message. */
    public CacheException(final String message) {
        super(message);
    }

    /** Creates a new CacheException with the given message and cause. */
    public CacheException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
