// DO NOT EDIT - auto-generated by alef
// alef:hash:b107bc945d7997683fc59b98218482e48ff0b2ea3acf3a8cfcc755c115fa07dd
package dev.kreuzberg;

public class CacheException extends KreuzbergErrorException {
    /** Creates a new CacheException with the given message. */
    public CacheException(final String message) {
        super(message);
    }

    /** Creates a new CacheException with the given message and cause. */
    public CacheException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
