// DO NOT EDIT - auto-generated by alef
// alef:hash:740c5012904701fee6acaa339c14e09b8d6aabec4913ba82b7a4ce9124721264
package dev.kreuzberg;

/**
 * A cache read or write operation failed.
 */
public class CacheException extends KreuzbergErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new CacheException with the given message. */
  public CacheException(final String message) {
    super(message);
  }

  /** Creates a new CacheException with the given message and cause. */
  public CacheException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
