// DO NOT EDIT - auto-generated by alef
// alef:hash:efd2140ced6a009a9d1d38ddc72b4db276a858d7af7ae2532a69917fe8e14cdc
package dev.kreuzberg;

/**
 * The extraction was cancelled via a `CancellationToken`.
 */
public class CancelledException extends KreuzbergErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new CancelledException with the given message. */
  public CancelledException(final String message) {
    super(message);
  }

  /** Creates a new CancelledException with the given message and cause. */
  public CancelledException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
