// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:740c5012904701fee6acaa339c14e09b8d6aabec4913ba82b7a4ce9124721264
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package dev.kreuzberg;

/**
 * Classification enrichment knob: how to label the document.
 */
public record ClassificationEnrichmentConfig(PageClassificationConfig config) {
}
