// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:c9dc9b974833d553bda62a8bd0befa85e3f3bcd4123126bb9f835b3c2d82debe
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package dev.kreuzberg;

/** Exception thrown when type conversion fails. */
@SuppressWarnings({"checkstyle:LineLength", "PMD"})
public class ConversionErrorException extends KreuzbergRsException {
  private static final long serialVersionUID = 1L;

  /** Creates a new ConversionErrorException. */
  public ConversionErrorException(final String message) {
    super(2, message);
  }

  /** Creates a new ConversionErrorException with a cause. */
  public ConversionErrorException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
