// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:932c299e263134c4cc188f80ca1d81c1eca95f4378df129af6ff63176a4ee7ed
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/sample_crate-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;

/**
 * dBASE field information.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = DbfFieldInfo.Builder.class)
public record DbfFieldInfo(
    @JsonProperty("name") String name,
    @JsonProperty("field_type") String fieldType
) {
    public static Builder builder() {
        return new Builder();
    }

    // CPD-OFF
    @JsonPOJOBuilder(withPrefix = "with", buildMethodName = "build")
    public static final class Builder {

private String name = "";
        @JsonProperty("field_type")
private String fieldType = "";

        /** Sets the name field. */
        @JsonProperty("name")
        public Builder withName(final String value) {
            this.name = value;
            return this;
        }

        /** Sets the fieldType field. */
        @JsonProperty("field_type")
        public Builder withFieldType(final String value) {
            this.fieldType = value;
            return this;
        }

        /** Builds the DbfFieldInfo instance. */
        public DbfFieldInfo build() {
            return new DbfFieldInfo(
                name,
                fieldType
            );
        }
    }
    // CPD-ON
}
