// DO NOT EDIT - auto-generated by alef
// alef:hash:4e15143f4af1ae8bafbdb1506ef057da924484c66a19483966333558ad437e75
package dev.kreuzberg;

public class EmbeddingException extends KreuzbergErrorException {
    /** Creates a new EmbeddingException with the given message. */
    public EmbeddingException(final String message) {
        super(message);
    }

    /** Creates a new EmbeddingException with the given message and cause. */
    public EmbeddingException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
