// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:4e553e5c2e32521a5d0fe24dbadf7d38f0d313bf8ccfc04eda48b442c241dec4
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * How the extracted text was produced.
 */
public enum ExtractionMethod {
    Native("native"),
    Ocr("ocr"),
    Mixed("mixed");

    /** The string value. */
    private final String value;

    ExtractionMethod(final String value) {
        this.value = value;
    }

    /** Returns the string value. */
    @JsonValue
    public String getValue() {
        return value;
    }

    /** Creates an instance from a string value. */
    @JsonCreator
    public static ExtractionMethod fromValue(final String value) {
        for (ExtractionMethod e : values()) {
            if (e.value.equalsIgnoreCase(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException("Unknown value: " + value);
    }

    /** Returns the wire-format string value (matches JSON serialization). */
    @Override
    public String toString() {
        return value;
    }
}
