// DO NOT EDIT - auto-generated by alef
// alef:hash:cd47a123c15e81eb202883752dbbe1e3b79560af4262761373429c24f46af3f1
package dev.kreuzberg;

/**
 * An image manipulation operation (resize, decode, DPI conversion) failed.
 */
public class ImageProcessingException extends KreuzbergErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new ImageProcessingException with the given message. */
  public ImageProcessingException(final String message) {
    super(message);
  }

  /** Creates a new ImageProcessingException with the given message and cause. */
  public ImageProcessingException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
