// DO NOT EDIT - auto-generated by alef
// alef:hash:740c5012904701fee6acaa339c14e09b8d6aabec4913ba82b7a4ce9124721264
package dev.kreuzberg;

/**
 * An image manipulation operation (resize, decode, DPI conversion) failed.
 */
public class ImageProcessingException extends KreuzbergErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new ImageProcessingException with the given message. */
  public ImageProcessingException(final String message) {
    super(message);
  }

  /** Creates a new ImageProcessingException with the given message and cause. */
  public ImageProcessingException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
