// DO NOT EDIT - auto-generated by alef
// alef:hash:129f6c78bc96b39658ce61eefcba84c48dda7c11a0dc9f36687849db17ea4295
package dev.kreuzberg;

/**
 * A file system or I/O operation failed. These errors always bubble up unchanged.
 */
public class IoException extends KreuzbergErrorException {
    /** Creates a new IoException with the given message. */
    public IoException(final String message) {
        super(message);
    }

    /** Creates a new IoException with the given message and cause. */
    public IoException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
