// DO NOT EDIT - auto-generated by alef
// alef:hash:e96e88b028ee650f7fa1df17d62630a20044cb98a78bfac698fceaa11d3c20a9
package dev.kreuzberg;

/**
 * An OCR engine returned an error or produced unusable output.
 */
public class OcrException extends KreuzbergErrorException {
    /** Creates a new OcrException with the given message. */
    public OcrException(final String message) {
        super(message);
    }

    /** Creates a new OcrException with the given message and cause. */
    public OcrException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
