// DO NOT EDIT - auto-generated by alef
// alef:hash:1ea2e31be2ea3875c4ac7b04e7c0c6025863bc99d4f62123c28991d3b085a679
package dev.kreuzberg;

/**
 * An OCR engine returned an error or produced unusable output.
 */
public class OcrException extends KreuzbergErrorException {
    /** Creates a new OcrException with the given message. */
    public OcrException(final String message) {
        super(message);
    }

    /** Creates a new OcrException with the given message and cause. */
    public OcrException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
