// DO NOT EDIT - auto-generated by alef
// alef:hash:65c81b783487ffa227bde3cbce25db912c1c454d597969afc02ea8924a5a781b
package dev.kreuzberg;

/**
 * An OCR engine returned an error or produced unusable output.
 */
public class OcrException extends KreuzbergErrorException {
    /** Creates a new OcrException with the given message. */
    public OcrException(final String message) {
        super(message);
    }

    /** Creates a new OcrException with the given message and cause. */
    public OcrException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
