// DO NOT EDIT - auto-generated by alef
// alef:hash:cd47a123c15e81eb202883752dbbe1e3b79560af4262761373429c24f46af3f1
package dev.kreuzberg;

/**
 * A catch-all for uncommon errors that do not fit another variant.
 */
public class OtherException extends KreuzbergErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new OtherException with the given message. */
  public OtherException(final String message) {
    super(message);
  }

  /** Creates a new OtherException with the given message and cause. */
  public OtherException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
