// DO NOT EDIT - auto-generated by alef
// alef:hash:efd2140ced6a009a9d1d38ddc72b4db276a858d7af7ae2532a69917fe8e14cdc
package dev.kreuzberg;

/**
 * A custom schema override was supplied but is not a JSON object.
 */
public class SchemaNotObjectException extends ResolveErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new SchemaNotObjectException with the given message. */
  public SchemaNotObjectException(final String message) {
    super(message);
  }

  /** Creates a new SchemaNotObjectException with the given message and cause. */
  public SchemaNotObjectException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
