// DO NOT EDIT - auto-generated by alef
// alef:hash:f1d9a4f3e11a0fb3b3f5a7ba8a0c897768ad230c7d2c8dfef213c1421b13b9fe
package dev.kreuzberg;

/**
 * The extraction operation exceeded the configured time limit.
 */
public class TimeoutException extends KreuzbergErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new TimeoutException with the given message. */
  public TimeoutException(final String message) {
    super(message);
  }

  /** Creates a new TimeoutException with the given message and cause. */
  public TimeoutException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
