// DO NOT EDIT - auto-generated by alef
// alef:hash:cd47a123c15e81eb202883752dbbe1e3b79560af4262761373429c24f46af3f1
package dev.kreuzberg;

/**
 * The extraction operation exceeded the configured time limit.
 */
public class TimeoutException extends KreuzbergErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new TimeoutException with the given message. */
  public TimeoutException(final String message) {
    super(message);
  }

  /** Creates a new TimeoutException with the given message and cause. */
  public TimeoutException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
