// DO NOT EDIT - auto-generated by alef
// alef:hash:65117d288912e7df5e977f99f2d09efab54c6797514ab3e309dac9b711595575
package dev.kreuzberg;

/**
 * Audio/video transcription failed.
 */
public class TranscriptionException extends KreuzbergErrorException {
    /** Creates a new TranscriptionException with the given message. */
    public TranscriptionException(final String message) {
        super(message);
    }

    /** Creates a new TranscriptionException with the given message and cause. */
    public TranscriptionException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
