// DO NOT EDIT - auto-generated by alef
// alef:hash:65c81b783487ffa227bde3cbce25db912c1c454d597969afc02ea8924a5a781b
package dev.kreuzberg;

/**
 * Audio/video transcription failed.
 */
public class TranscriptionException extends KreuzbergErrorException {
    /** Creates a new TranscriptionException with the given message. */
    public TranscriptionException(final String message) {
        super(message);
    }

    /** Creates a new TranscriptionException with the given message and cause. */
    public TranscriptionException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
