// DO NOT EDIT - auto-generated by alef
// alef:hash:e96e88b028ee650f7fa1df17d62630a20044cb98a78bfac698fceaa11d3c20a9
package dev.kreuzberg;

/**
 * The document's MIME type is not supported by any registered extractor.
 */
public class UnsupportedFormatException extends KreuzbergErrorException {
    /** Creates a new UnsupportedFormatException with the given message. */
    public UnsupportedFormatException(final String message) {
        super(message);
    }

    /** Creates a new UnsupportedFormatException with the given message and cause. */
    public UnsupportedFormatException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
