// DO NOT EDIT - auto-generated by alef
// alef:hash:4e553e5c2e32521a5d0fe24dbadf7d38f0d313bf8ccfc04eda48b442c241dec4
package dev.kreuzberg;

public class ValidationException extends KreuzbergErrorException {
    /** Creates a new ValidationException with the given message. */
    public ValidationException(final String message) {
        super(message);
    }

    /** Creates a new ValidationException with the given message and cause. */
    public ValidationException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
