// Generated by alef. Do not edit by hand.
// alef:hash:e96e88b028ee650f7fa1df17d62630a20044cb98a78bfac698fceaa11d3c20a9

pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

plugins {
    id("org.gradle.toolchains.foojay-resolver-convention") version "1.0.0"
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.name = "kreuzberg-e2e"
