// Generated by alef. Do not edit by hand.
// alef:hash:38dce430f8d9bea3dcf8465197cc598552462cd7a5930cc5e7e769e1d0990c01

pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

plugins {
    id("org.gradle.toolchains.foojay-resolver-convention") version "1.0.0"
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.name = "xberg-android"
