// Generated by alef. Do not edit by hand.
// alef:hash:356ed0ad572128a92e2a68ca531b92cd783973ff49e6e7f17fef8212f0216bcf
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
    "NestedBlockDepth",
    "ReturnCount",
    "UnusedParameter",
)

package io.xberg

/**
 * A single file extracted from an archive.
 *
 * When archives (ZIP, TAR, 7Z, GZIP) are extracted with recursive extraction enabled, each
 * processable file produces its own full `ExtractedDocument`.
 */
data class ArchiveEntry(
    /** Archive-relative file path (e.g. "folder/document.pdf"). */
    val path: String,
    /** Detected MIME type of the file. */
    val mimeType: String,
    /** Full extraction result for this file. */
    val result: ExtractedDocument,
)
