// Generated by alef. Do not edit by hand.
// alef:hash:c1dfa38f25cb4a4f3ae999d5f20b3224282c944b5460083a05218399c26fa935

package io.xberg

object DocumentExtractorBridge {
    private val registered = mutableMapOf<String, IDocumentExtractor>()

    fun register(impl: IDocumentExtractor): Unit {
        val name = impl.name()
        registered[name] = impl
        XbergBridge.nativeRegisterDocumentExtractor(DocumentExtractorJniDispatcher(impl))
    }

    fun unregister(name: String): Unit {
        registered.remove(name)
        XbergBridge.nativeUnregisterDocumentExtractor(name)
    }

    fun clearAll(): Unit {
        registered.clear()
        XbergBridge.nativeClearDocumentExtractors()
    }

    fun getAll(): Map<String, IDocumentExtractor> = registered.toMap()
}
