// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:5a84e025da24b5e6c7a19c5d55becf5c3d4bf3687d62fe536fe4b83ebb1c75a8
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonInclude;
import org.jspecify.annotations.Nullable;

/**
 * Batch item for file extraction.
 *
 * Used with {@code batch_extract_files} and {@code batch_extract_files_sync} to represent a single file in a batch
 * extraction job.
 */
@SuppressWarnings("checkstyle:LineLength")
@JsonInclude(JsonInclude.Include.NON_ABSENT)
public record BatchFileItem(java.nio.file.Path path, @Nullable FileExtractionConfig config) {
}
