// DO NOT EDIT - auto-generated by alef
// alef:hash:7afad4fc5c96dedf753a20dd49facc3bf058e3504863a264efebe38f7798ce2b
package dev.kreuzberg;

public class CancelledException extends KreuzbergErrorException {
    /** Creates a new CancelledException with the given message. */
    public CancelledException(final String message) {
        super(message);
    }

    /** Creates a new CancelledException with the given message and cause. */
    public CancelledException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
