// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:2a589953cc7f658291d53507f5da33a3483f4011b9a8642e0e22810c267d2d61
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import org.jspecify.annotations.Nullable;

/**
 * MIME type detection response.
 */
@SuppressWarnings("checkstyle:LineLength")
@JsonInclude(JsonInclude.Include.NON_ABSENT)
public record DetectResponse(
        /** Detected MIME type */
        @JsonProperty("mime_type") String mimeType,
        /** Original filename (if provided) */
        @Nullable String filename) {
}
