// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:c47f78eee1655268c2fca6269d7e614686f8ba97a641a27528e81e2f3632f12a
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonInclude;
import org.jspecify.annotations.Nullable;

/**
 * Image element in Djot.
 */
@SuppressWarnings("checkstyle:LineLength")
@JsonInclude(JsonInclude.Include.NON_ABSENT)
public record DjotImage(
        /** Image source URL or path */
        String src,
        /** Alternative text */
        String alt,
        /** Optional title */
        @Nullable String title,
        /** Element attributes */
        @Nullable String attributes) {
}
