// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:31856b6087898cd8087ed35363d91d1c5143551f6377783c014049a5df050e3e
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import java.util.Optional;
import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;

/**
 * Configuration for email extraction.
 */
@SuppressWarnings("checkstyle:LineLength")
@JsonPOJOBuilder(withPrefix = "with")
public class EmailConfigBuilder {

    private Optional<Integer> msgFallbackCodepage = Optional.empty();

    /** Sets the msgFallbackCodepage field. */
    public EmailConfigBuilder withMsgFallbackCodepage(final Optional<Integer> value) {
        this.msgFallbackCodepage = value;
        return this;
    }

    /** Builds the EmailConfig instance. */
    public EmailConfig build() {
        return new EmailConfig(msgFallbackCodepage.orElse(null));
    }
}
