// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:f94d07617a22a9f10e685c457443870b56f78cf7a51a68b4ca30953cae4786be
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonInclude;
import org.jspecify.annotations.Nullable;

/**
 * Embedding request for generating embeddings from text.
 */
@SuppressWarnings("checkstyle:LineLength")
@JsonInclude(JsonInclude.Include.NON_ABSENT)
public record EmbedRequest(
        /** Text strings to generate embeddings for (at least one non-empty string required) */
        @JsonInclude(JsonInclude.Include.NON_NULL) List<String> texts,
        /** Optional embedding configuration (model, batch size, etc.) */
        @Nullable EmbeddingConfig config) {
}
