// DO NOT EDIT - auto-generated by alef
// alef:hash:927088f159543b3941483886d01cf0960f7ce0b06077c268fe13b10a7f14d06d
package dev.kreuzberg;

public class LockPoisonedException extends KreuzbergErrorException {
    /** Creates a new LockPoisonedException with the given message. */
    public LockPoisonedException(final String message) {
        super(message);
    }

    /** Creates a new LockPoisonedException with the given message and cause. */
    public LockPoisonedException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
