// DO NOT EDIT - auto-generated by alef
// alef:hash:5b80b21c41e5771f77e0f532db1cb7564dd68a51614df038d49897e345e59c36
package dev.kreuzberg;

public class LockPoisonedException extends KreuzbergErrorException {
    /** Creates a new LockPoisonedException with the given message. */
    public LockPoisonedException(final String message) {
        super(message);
    }

    /** Creates a new LockPoisonedException with the given message and cause. */
    public LockPoisonedException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
