// DO NOT EDIT - auto-generated by alef
// alef:hash:dbc1f980e2eac4cafc4ab5de4fc5db4a3e0130163d603a0ec74166d25e825ae6
package dev.kreuzberg;

public class MissingDependencyException extends KreuzbergErrorException {
    /** Creates a new MissingDependencyException with the given message. */
    public MissingDependencyException(final String message) {
        super(message);
    }

    /** Creates a new MissingDependencyException with the given message and cause. */
    public MissingDependencyException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
