// DO NOT EDIT - auto-generated by alef
// alef:hash:1dcff3f2ec341c42c32cd45d3f1e35be0ebdf8e6bf57428e1907a817c424329a
package dev.kreuzberg;

public class ParsingException extends KreuzbergErrorException {
    /** Creates a new ParsingException with the given message. */
    public ParsingException(final String message) {
        super(message);
    }

    /** Creates a new ParsingException with the given message and cause. */
    public ParsingException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
