// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:e38bdbd5e765ebbbf2ac0d0b3a42742387f18e8dbc8b7ed68a9ce86b2ef1217f
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;

/**
 * RAKE-specific parameters.
 */
@SuppressWarnings("checkstyle:LineLength")
@JsonPOJOBuilder(withPrefix = "with")
public class RakeParamsBuilder {

    private long minWordLength = 0;
    private long maxWordsPerPhrase = 0;

    /** Sets the minWordLength field. */
    public RakeParamsBuilder withMinWordLength(final long value) {
        this.minWordLength = value;
        return this;
    }

    /** Sets the maxWordsPerPhrase field. */
    public RakeParamsBuilder withMaxWordsPerPhrase(final long value) {
        this.maxWordsPerPhrase = value;
        return this;
    }

    /** Builds the RakeParams instance. */
    public RakeParams build() {
        return new RakeParams(minWordLength, maxWordsPerPhrase);
    }
}
