// DO NOT EDIT - auto-generated by alef
// alef:hash:877f7359f461ff45c579b70a0a4934fc08138a1f7b5928ced73a6760ecf6e43b
package dev.kreuzberg;

public class SecurityException extends KreuzbergErrorException {
    /** Creates a new SecurityException with the given message. */
    public SecurityException(final String message) {
        super(message);
    }

    /** Creates a new SecurityException with the given message and cause. */
    public SecurityException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
