// DO NOT EDIT - auto-generated by alef
// alef:hash:ba3cce741c514d5896a9ea72d79c79f51bdd590e0b19ecefb9f89469765a272f
package dev.kreuzberg;

public class SerializationException extends KreuzbergErrorException {
    /** Creates a new SerializationException with the given message. */
    public SerializationException(final String message) {
        super(message);
    }

    /** Creates a new SerializationException with the given message and cause. */
    public SerializationException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
