// DO NOT EDIT - auto-generated by alef
// alef:hash:d06eab21e4cadd91b74398e9834f9ff466cc24b84289e3b6aa2b89c9e4d073ab
package dev.kreuzberg;

public class TimeoutException extends KreuzbergErrorException {
    /** Creates a new TimeoutException with the given message. */
    public TimeoutException(final String message) {
        super(message);
    }

    /** Creates a new TimeoutException with the given message and cause. */
    public TimeoutException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
