// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:7284ca5a5a970c1212b5b72f942ef751bdad7623d68a324d3c3f7681fb896944
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;

/**
 * XML metadata extracted during XML parsing.
 *
 * Provides statistics about XML document structure.
 */
@SuppressWarnings("checkstyle:LineLength")
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = XmlMetadataBuilder.class)
public record XmlMetadata(
        /** Total number of XML elements processed */
        @JsonProperty("element_count") long elementCount, /** List of unique element tag names (sorted) */
        @JsonInclude(JsonInclude.Include.NON_NULL) @JsonProperty("unique_elements") List<String> uniqueElements) {
    public static XmlMetadataBuilder builder() {
        return new XmlMetadataBuilder();
    }
}
