# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:ac64aa42c4d57c746b4c8b8a7dad2e60780b30868d39a501a6a9f9cf8145d6f0
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.AccelerationConfig do
  @moduledoc "Hardware acceleration configuration for ONNX Runtime models."

  defstruct provider: :auto,
            device_id: 0
end
