# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:c5d8764c0ab60cbd69d2d52426b8988812f6d7460cd0505a6ec8a78c876c474a
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ArchiveEntry do
  @moduledoc "A single file extracted from an archive."

  defstruct path: nil,
            mime_type: nil,
            result: nil
end
