# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:6a863205e7a486a4e1b97dac288554ebbf65a8b3ad1aaa6799965109e6543cd4
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.BatchFileItem do
  @moduledoc """
  Batch item for file extraction.

  Used with `batch_extract_files` and `batch_extract_files_sync`
  to represent a single file in a batch extraction job.
  """

  @typedoc "Batch item for file extraction."
  @type t :: %__MODULE__{
          path: String.t() | nil,
          config: map() | nil
        }

  defstruct path: nil,
            config: nil
end
