# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:6a863205e7a486a4e1b97dac288554ebbf65a8b3ad1aaa6799965109e6543cd4
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.CellChange do
  @moduledoc """
  A single changed cell within a table.

  Defined here (rather than only in `crate::diff`) so `RevisionDelta` can
  reference it unconditionally, without requiring the `diff` Cargo feature.
  `crate::diff` re-exports this type verbatim.
  """

  @typedoc "A single changed cell within a table."
  @type t :: %__MODULE__{
          row: non_neg_integer(),
          col: non_neg_integer(),
          from: String.t() | nil,
          to: String.t() | nil
        }

  defstruct row: 0,
            col: 0,
            from: nil,
            to: nil
end
