# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:740c5012904701fee6acaa339c14e09b8d6aabec4913ba82b7a4ce9124721264
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.ChunkInfo do
  @moduledoc "Information about a single chunk."

  @typedoc "Information about a single chunk."
  @type t :: %__MODULE__{
          index: non_neg_integer(),
          pages: map(),
          estimated_time_ms: non_neg_integer()
        }

  defstruct index: 0,
            pages: nil,
            estimated_time_ms: 0
end
