# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:b0d91fb62af08d6df7113b91209e9869bee112506d29e5da63e938bfffebaadf
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/sample_crate-dev/alef
defmodule Kreuzberg.Chunk do
  @moduledoc """
  A text chunk with optional embedding and metadata.

  Chunks are created when chunking is enabled in `ExtractionConfig`. Each chunk
  contains the text content, optional embedding vector (if embedding generation
  is configured), and metadata about its position in the document.
  """

  @typedoc "A text chunk with optional embedding and metadata."
  @type t :: %__MODULE__{
          content: String.t() | nil,
          chunk_type: String.t() | nil,
          embedding: [float()] | nil,
          metadata: map()
        }

  defstruct content: nil,
            chunk_type: :unknown,
            embedding: nil,
            metadata: nil
end
