# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:f1d9a4f3e11a0fb3b3f5a7ba8a0c897768ad230c7d2c8dfef213c1421b13b9fe
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.ChunkingDecision do
  @moduledoc "The chunking decision made by the analyzer."

  @typedoc "The chunking decision made by the analyzer."
  @type t :: term()

  @typedoc "Process without chunking (small file, text layer detected, etc.)"
  @type no_chunking :: %{type: :no_chunking, reason: map()}
  @typedoc "Chunk according to plan."
  @type chunk :: %{type: :chunk, plan: Kreuzberg.ChunkPlan.t()}
  @typedoc "Use user-provided chunk overrides."
  @type use_overrides :: %{type: :use_overrides, user_chunks: [map()]}
end
