# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:101f93f77893c2c7989723625cc5537a934c702f60a360b93d41055b40c41ceb
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.ClassificationLabel do
  @moduledoc "A single label + confidence pair."

  @typedoc "A single label + confidence pair."
  @type t :: %__MODULE__{
          label: String.t() | nil,
          confidence: float() | nil
        }

  defstruct label: nil,
            confidence: nil
end
