# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:f1d9a4f3e11a0fb3b3f5a7ba8a0c897768ad230c7d2c8dfef213c1421b13b9fe
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.ConfidenceSignals do
  @moduledoc """
  Input signals for confidence scoring.

  Caller fills these from the extraction result and the LLM response.
  """

  @typedoc "Input signals for confidence scoring."
  @type t :: %__MODULE__{
          text_coverage: float(),
          ocr_aggregate: float() | nil,
          schema_compliance: String.t() | nil
        }

  defstruct text_coverage: 0.0,
            ocr_aggregate: nil,
            schema_compliance: :all_valid
end
