# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:1b01ce38e69baf9c075239dad791f7fe557e8b701cd1338c25b8531fcc364b11
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.CsvMetadata do
  @moduledoc "CSV/TSV file metadata."

  defstruct row_count: 0,
            column_count: 0,
            delimiter: nil,
            has_header: false,
            column_types: []
end
