# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:43b856a258f29d86e138fbaccaf7f80a7ef7c29bf25864bb349906e5ec47779e
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.DbfFieldInfo do
  @moduledoc "dBASE field information."

  defstruct name: nil,
            field_type: nil
end
