# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:4e15143f4af1ae8bafbdb1506ef057da924484c66a19483966333558ad437e75
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.DbfFieldInfo do
  @moduledoc "dBASE field information."

  @typedoc "dBASE field information."
  @type t :: %__MODULE__{
          name: String.t() | nil,
          field_type: String.t() | nil
        }

  defstruct name: nil,
            field_type: nil
end
