# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:93412321bd28f0ed845787abb2121f097b84d2a3b6a9c0c335736cd83a3ecc37
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.DetectResponse do
  @moduledoc "MIME type detection response."

  defstruct mime_type: nil,
            filename: nil
end
