# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:eff221100d90121d3c6a62b9fcfb209f8406380704931621af9211dafc848733
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.DetectMimeTypeParams do
  @moduledoc "Request parameters for MIME type detection."

  defstruct path: nil,
            use_content: false
end
