# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:6a863205e7a486a4e1b97dac288554ebbf65a8b3ad1aaa6799965109e6543cd4
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.DiffHunk do
  @moduledoc "A single contiguous hunk in a unified diff."

  @typedoc "A single contiguous hunk in a unified diff."
  @type t :: %__MODULE__{
          from_line: non_neg_integer(),
          from_count: non_neg_integer(),
          to_line: non_neg_integer(),
          to_count: non_neg_integer(),
          lines: [String.t() | nil]
        }

  defstruct from_line: 0,
            from_count: 0,
            to_line: 0,
            to_count: 0,
            lines: []
end
