# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:6a8400ffd6e27c557ffd585458e080034774f33340cc49f53c2cb322a0da85dd
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.DiffHunk do
  @moduledoc "A single contiguous hunk in a unified diff."

  @typedoc "A single contiguous hunk in a unified diff."
  @type t :: %__MODULE__{
          from_line: non_neg_integer(),
          from_count: non_neg_integer(),
          to_line: non_neg_integer(),
          to_count: non_neg_integer(),
          lines: [String.t() | nil]
        }

  defstruct from_line: 0,
            from_count: 0,
            to_line: 0,
            to_count: 0,
            lines: []
end
