# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:55cf9a5906feb590d69168ad964e432c354c1464aef4b19f04e94317d4a3a74f
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.DjotImage do
  @moduledoc "Image element in Djot."

  @typedoc "Image element in Djot."
  @type t :: %__MODULE__{
          src: String.t() | nil,
          alt: String.t() | nil,
          title: String.t() | nil
        }

  defstruct src: nil,
            alt: nil,
            title: nil
end
