# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:0f9cc38afb852ae20d59d873bebe8c504acff8b416592e6f759c649b38d5676b
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.DjotImage do
  @moduledoc "Image element in Djot."

  defstruct src: nil,
            alt: nil,
            title: nil,
            attributes: nil
end
