# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:96e3f3120fbb6545e27dca12fbb2be5238120f4cbd98c597a073c296e5df7366
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.DocumentRelationship do
  @moduledoc "A resolved relationship between two nodes in the document tree."

  @typedoc "A resolved relationship between two nodes in the document tree."
  @type t :: %__MODULE__{
          source: non_neg_integer(),
          target: non_neg_integer(),
          kind: String.t() | nil
        }

  defstruct source: 0,
            target: 0,
            kind: :footnote_reference
end
