# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:ec91dbee1d83bc2f7b5959533d5b31028a743dc0e13422b02fefb71efece8f0e
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.Element do
  @moduledoc "Semantic element extracted from document."

  @type t :: %__MODULE__{
          element_id: String.t() | nil,
          element_type: String.t() | nil,
          text: String.t() | nil,
          metadata: map()
        }

  defstruct element_id: nil,
            element_type: :title,
            text: nil,
            metadata: nil
end
