# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:6a863205e7a486a4e1b97dac288554ebbf65a8b3ad1aaa6799965109e6543cd4
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.ElementMetadata do
  @moduledoc "Metadata for a semantic element."

  @typedoc "Metadata for a semantic element."
  @type t :: %__MODULE__{
          page_number: non_neg_integer() | nil,
          filename: String.t() | nil,
          coordinates: map() | nil,
          element_index: non_neg_integer() | nil,
          additional: map()
        }

  defstruct page_number: nil,
            filename: nil,
            coordinates: nil,
            element_index: nil,
            additional: %{}
end
