# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:c9dc9b974833d553bda62a8bd0befa85e3f3bcd4123126bb9f835b3c2d82debe
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.EmailAttachment do
  @moduledoc """
  Email attachment representation.

  Contains metadata and optionally the content of an email attachment.
  """

  @typedoc "Email attachment representation."
  @type t :: %__MODULE__{
          name: String.t() | nil,
          filename: String.t() | nil,
          mime_type: String.t() | nil,
          size: non_neg_integer() | nil,
          is_image: boolean(),
          data: binary() | nil
        }

  defstruct name: nil,
            filename: nil,
            mime_type: nil,
            size: nil,
            is_image: false,
            data: nil
end
