# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:caebc3d131b03cb582c1cfce436a09b785978f3583c9aa2c5949daafccaf63ae
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.EmailConfig do
  @moduledoc "Configuration for email extraction."

  @typedoc "Configuration for email extraction."
  @type t :: %__MODULE__{
          msg_fallback_codepage: non_neg_integer() | nil
        }

  defstruct msg_fallback_codepage: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
