# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:caebc3d131b03cb582c1cfce436a09b785978f3583c9aa2c5949daafccaf63ae
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.EmbeddedChanges do
  @moduledoc "Changes to embedded archive children between two results."

  @typedoc "Changes to embedded archive children between two results."
  @type t :: %__MODULE__{
          added: [map()],
          removed: [map()],
          changed: [map()]
        }

  defstruct added: [],
            removed: [],
            changed: []
end
