# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a21bbc6932a2537aa10c6019978e22f23069915ae1ec61b1fcaec67730b4290b
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.EmbeddedFile do
  @moduledoc "Embedded file descriptor extracted from the PDF name tree."

  defstruct name: "",
            data: "",
            mime_type: nil
end
