# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:6a8400ffd6e27c557ffd585458e080034774f33340cc49f53c2cb322a0da85dd
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.ErrorMetadata do
  @moduledoc "Error metadata (for batch operations)."

  @typedoc "Error metadata (for batch operations)."
  @type t :: %__MODULE__{
          error_type: String.t() | nil,
          message: String.t() | nil
        }

  defstruct error_type: nil,
            message: nil
end
