# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:9f578f2470bbec7549733c73ae6b7d724fd2f5f58441654ef1d408d21e501c7d
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.ExcelSheet do
  @moduledoc """
  Single Excel worksheet.

  Represents one sheet from an Excel workbook with its content
  converted to Markdown format and dimensional statistics.
  """

  @typedoc "Single Excel worksheet."
  @type t :: %__MODULE__{
          name: String.t() | nil,
          markdown: String.t() | nil,
          row_count: non_neg_integer(),
          col_count: non_neg_integer(),
          cell_count: non_neg_integer(),
          table_cells: [[String.t()]] | nil
        }

  defstruct name: nil,
            markdown: nil,
            row_count: 0,
            col_count: 0,
            cell_count: 0,
            table_cells: nil
end
