# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a185f03b4e1b5c2037d5425d0df62972a13b87966bb430c22367d356c0dd4c4e
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ExcelMetadata do
  @moduledoc "Excel/spreadsheet format metadata."

  defstruct sheet_count: 0,
            sheet_names: []
end
