# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:efd2140ced6a009a9d1d38ddc72b4db276a858d7af7ae2532a69917fe8e14cdc
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.ExtractedUri do
  @moduledoc """
  A URI extracted from a document.

  Represents any link, reference, or resource pointer found during extraction.
  The `kind` field classifies the URI semantically, while `label` carries
  optional human-readable display text.
  """

  @typedoc "A URI extracted from a document."
  @type t :: %__MODULE__{
          url: String.t() | nil,
          label: String.t() | nil,
          page: non_neg_integer() | nil,
          kind: String.t() | nil
        }

  defstruct url: nil,
            label: nil,
            page: nil,
            kind: :hyperlink
end
