# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:6a8400ffd6e27c557ffd585458e080034774f33340cc49f53c2cb322a0da85dd
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.ExtractionMethod do
  @moduledoc "How the extracted text was produced."

  @typedoc "How the extracted text was produced."
  @type t :: :native | :ocr | :mixed

  @native :native
  @ocr :ocr
  @mixed :mixed

  @doc "Text extracted directly from the document's native format (no OCR)."
  @spec native() :: t()
  def native, do: @native
  @doc "All text was obtained via OCR (e.g. scanned image-only PDF)."
  @spec ocr() :: t()
  def ocr, do: @ocr
  @doc "Text came from a combination of native extraction and OCR."
  @spec mixed() :: t()
  def mixed, do: @mixed
end
