# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:6a863205e7a486a4e1b97dac288554ebbf65a8b3ad1aaa6799965109e6543cd4
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.ExtractedUri do
  @moduledoc """
  A URI extracted from a document.

  Represents any link, reference, or resource pointer found during extraction.
  The `kind` field classifies the URI semantically, while `label` carries
  optional human-readable display text.
  """

  @typedoc "A URI extracted from a document."
  @type t :: %__MODULE__{
          url: String.t() | nil,
          label: String.t() | nil,
          page: non_neg_integer() | nil,
          kind: String.t() | nil
        }

  defstruct url: nil,
            label: nil,
            page: nil,
            kind: :hyperlink
end
