# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:797db4307b3e11ce4d8fb2dffabc71c91c91b8dd588801b183c6c58388e976ca
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ExtractResponse do
  @moduledoc "Extraction response (list of results)."

  alias Kreuzberg.Native

  defstruct [:ref]

  @type t :: %__MODULE__{ref: reference()}
end
