# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:9f578f2470bbec7549733c73ae6b7d724fd2f5f58441654ef1d408d21e501c7d
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.FictionBookMetadata do
  @moduledoc "FictionBook (FB2) metadata."

  @typedoc "FictionBook (FB2) metadata."
  @type t :: %__MODULE__{
          genres: [String.t()],
          sequences: [String.t()],
          annotation: String.t() | nil
        }

  defstruct genres: [],
            sequences: [],
            annotation: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
