# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:b107bc945d7997683fc59b98218482e48ff0b2ea3acf3a8cfcc755c115fa07dd
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.GlineBackend do
  @moduledoc """
  kreuzberg-gliner-rs ONNX backend wrapper.

  Holds an initialised [`GLiNER<SpanMode>`] behind an `Arc<Mutex<...>>` so the
  model can be safely shared across async tasks (inference is synchronous and
  serialised internally by the mutex).
  """

  @typedoc "kreuzberg-gliner-rs ONNX backend wrapper."
  @type t :: %__MODULE__{
          repo_id: String.t() | nil,
          model_path: String.t() | nil,
          tokenizer_path: String.t() | nil
        }

  defstruct repo_id: nil,
            model_path: nil,
            tokenizer_path: nil
end
