# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:b0d91fb62af08d6df7113b91209e9869bee112506d29e5da63e938bfffebaadf
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/sample_crate-dev/alef
defmodule Kreuzberg.GridCell do
  @moduledoc "Individual grid cell with position and span metadata."

  @typedoc "Individual grid cell with position and span metadata."
  @type t :: %__MODULE__{
          content: String.t() | nil,
          row: non_neg_integer(),
          col: non_neg_integer(),
          row_span: non_neg_integer(),
          col_span: non_neg_integer(),
          is_header: boolean(),
          bbox: map() | nil
        }

  defstruct content: nil,
            row: 0,
            col: 0,
            row_span: 0,
            col_span: 0,
            is_header: false,
            bbox: nil
end
