# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:5d1e47597d6ea5344faab8f7b357976d4e0ece4dcbbde4cd8cb3d54af227acb1
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.HeadingContext do
  @moduledoc "Heading context for a chunk within a Markdown document."

  defstruct headings: []
end
