# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:1ea2e31be2ea3875c4ac7b04e7c0c6025863bc99d4f62123c28991d3b085a679
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.HierarchicalBlock do
  @moduledoc """
  A text block with hierarchy level assignment.

  Represents a block of text with semantic heading information extracted from
  font size clustering and hierarchical analysis.
  """

  @typedoc "A text block with hierarchy level assignment."
  @type t :: %__MODULE__{
          text: String.t() | nil,
          font_size: float(),
          level: String.t() | nil
        }

  defstruct text: nil,
            font_size: 0.0,
            level: nil
end
