# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:9f578f2470bbec7549733c73ae6b7d724fd2f5f58441654ef1d408d21e501c7d
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.HierarchicalBlock do
  @moduledoc """
  A text block with hierarchy level assignment.

  Represents a block of text with semantic heading information extracted from
  font size clustering and hierarchical analysis.
  """

  @typedoc "A text block with hierarchy level assignment."
  @type t :: %__MODULE__{
          text: String.t() | nil,
          font_size: float(),
          level: String.t() | nil
        }

  defstruct text: nil,
            font_size: 0.0,
            level: nil
end
