# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:6a8400ffd6e27c557ffd585458e080034774f33340cc49f53c2cb322a0da85dd
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.ImageMetadataType do
  @moduledoc "Image element metadata."

  @typedoc "Image element metadata."
  @type t :: %__MODULE__{
          src: String.t() | nil,
          alt: String.t() | nil,
          title: String.t() | nil,
          image_type: String.t() | nil
        }

  defstruct src: nil,
            alt: nil,
            title: nil,
            image_type: :data_uri
end
