# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:e40ad549476b87d3a1cac33feb564a52b9fc6ca2f4e12e9986ce84fa4ce2a21e
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ImageMetadata do
  @moduledoc "Image metadata extracted from image files."

  @type t :: %__MODULE__{
          width: non_neg_integer(),
          height: non_neg_integer(),
          format: String.t() | nil,
          exif: map()
        }

  defstruct width: 0,
            height: 0,
            format: nil,
            exif: %{}
end
