# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:55cf9a5906feb590d69168ad964e432c354c1464aef4b19f04e94317d4a3a74f
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.InlineElement do
  @moduledoc """
  Inline element within a block.

  Represents text with formatting, links, images, etc.
  """

  @typedoc "Inline element within a block."
  @type t :: %__MODULE__{
          element_type: String.t() | nil,
          content: String.t() | nil,
          metadata: map() | nil
        }

  defstruct element_type: :text,
            content: nil,
            metadata: nil
end
