# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:129f6c78bc96b39658ce61eefcba84c48dda7c11a0dc9f36687849db17ea4295
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.KeywordConfig do
  @moduledoc "Keyword extraction configuration."

  @typedoc "Keyword extraction configuration."
  @type t :: %__MODULE__{
          algorithm: String.t() | nil,
          max_keywords: non_neg_integer(),
          min_score: float(),
          language: String.t() | nil,
          yake_params: map() | nil,
          rake_params: map() | nil
        }

  defstruct algorithm: :yake,
            max_keywords: 10,
            min_score: 0,
            language: nil,
            yake_params: nil,
            rake_params: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
