# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:035a9786c0d6cf2436e0790caa5dfba499b0d7ff6d84b84c65f2c22edbcc4a6f
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.Keyword do
  @moduledoc "Extracted keyword with metadata."

  defstruct text: nil,
            score: 0.0,
            algorithm: :yake,
            positions: nil
end
