# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:fc80bf10cd9e5e7f08a9c541fcd6220d7342df63fa1e17d6ecf17827e285a57b
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.KeywordAlgorithm do
  @moduledoc "Keyword algorithm selection."

  @typedoc "Keyword algorithm selection."
  @type t :: :yake | :rake

  @yake :yake
  @rake :rake

  @doc "YAKE (Yet Another Keyword Extractor) - statistical approach"
  @spec yake() :: t()
  def yake, do: @yake
  @doc "RAKE (Rapid Automatic Keyword Extraction) - co-occurrence based"
  @spec rake() :: t()
  def rake, do: @rake
end
