# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:1265616ed80e93c5694207e64e5b981361944d3d137ec8ca43d5de968f8e43ec
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.Keyword do
  @moduledoc "Extracted keyword with metadata."

  defstruct text: "",
            score: 0.0,
            algorithm: :yake,
            positions: nil
end
