# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:483413d837c40cc4f37cd35853ff42b04c45d4f1dbb242be6a28c45d9bba6358
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.KeywordConfig do
  @moduledoc "Keyword extraction configuration."

  defstruct algorithm: :yake,
            max_keywords: 10,
            min_score: 0,
            ngram_range: [],
            language: "",
            yake_params: nil,
            rake_params: nil
end
