# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:129f6c78bc96b39658ce61eefcba84c48dda7c11a0dc9f36687849db17ea4295
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.LayoutDetection do
  @moduledoc "A single layout detection result."

  @typedoc "A single layout detection result."
  @type t :: %__MODULE__{
          class_name: String.t() | nil,
          confidence: float(),
          bbox: map()
        }

  defstruct class_name: :caption,
            confidence: 0.0,
            bbox: nil
end
