# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:6a8400ffd6e27c557ffd585458e080034774f33340cc49f53c2cb322a0da85dd
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.LayoutDetection do
  @moduledoc "A single layout detection result."

  @typedoc "A single layout detection result."
  @type t :: %__MODULE__{
          class_name: String.t() | nil,
          confidence: float(),
          bbox: map()
        }

  defstruct class_name: :caption,
            confidence: 0.0,
            bbox: nil
end
