# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:101f93f77893c2c7989723625cc5537a934c702f60a360b93d41055b40c41ceb
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.LinkMetadata do
  @moduledoc "Link element metadata."

  @typedoc "Link element metadata."
  @type t :: %__MODULE__{
          href: String.t() | nil,
          text: String.t() | nil,
          title: String.t() | nil,
          link_type: String.t() | nil,
          rel: [String.t()]
        }

  defstruct href: nil,
            text: nil,
            title: nil,
            link_type: :anchor,
            rel: []
end
