# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:2e08f55dd5fe92897b0fa1be8f8e93382fb4d333fa345bf02b806320d646729f
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.LlmUsage do
  @moduledoc "Token usage and cost data for a single LLM call made during extraction."

  defstruct model: "",
            source: "",
            input_tokens: 0,
            output_tokens: 0,
            total_tokens: 0,
            estimated_cost: 0.0,
            finish_reason: ""
end
