# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:3f2554dbae111b3006735ac35ede1dc2e4479f6f382d12d39c0d233eaf3d93ed
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.LlmConfig do
  @moduledoc "Configuration for an LLM provider/model via liter-llm."

  defstruct model: "",
            api_key: "",
            base_url: "",
            timeout_secs: 0,
            max_retries: 0,
            temperature: 0.0,
            max_tokens: 0
end
