# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:f868e7ca6c3c102d9d8fffe52f1a1d8ead1db0b348a9e1c4c08411e9cd6501b0
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.LlmUsage do
  @moduledoc "Token usage and cost data for a single LLM call made during extraction."

  defstruct model: nil,
            source: nil,
            input_tokens: 0,
            output_tokens: 0,
            total_tokens: 0,
            estimated_cost: 0.0,
            finish_reason: nil
end
