# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:b0d91fb62af08d6df7113b91209e9869bee112506d29e5da63e938bfffebaadf
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/sample_crate-dev/alef
defmodule Kreuzberg.LlmConfig do
  @moduledoc """
  Configuration for an LLM provider/model via liter-llm.

  Each feature (VLM OCR, VLM embeddings, structured extraction) carries
  its own `LlmConfig`, allowing different providers per feature.

  # Example

  ```toml
  [structured_extraction.llm]
  model = "openai/gpt-4o"
  api_key = "sk-..."  # or use KREUZBERG_LLM_API_KEY env var
  ```
  """

  @typedoc "Configuration for an LLM provider/model via liter-llm."
  @type t :: %__MODULE__{
          model: String.t() | nil,
          api_key: String.t() | nil,
          base_url: String.t() | nil,
          timeout_secs: non_neg_integer() | nil,
          max_retries: non_neg_integer() | nil,
          temperature: float() | nil,
          max_tokens: non_neg_integer() | nil
        }

  defstruct model: nil,
            api_key: nil,
            base_url: nil,
            timeout_secs: nil,
            max_retries: nil,
            temperature: nil,
            max_tokens: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
