# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:f16ac1b44801416fcfcdefc44425af52b18eedc880e9b25386abd61b05836589
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.LlmUsage do
  @moduledoc """
  Token usage and cost data for a single LLM call made during extraction.

  Populated when VLM OCR, structured extraction, or LLM-based embeddings
  are used. Multiple entries may be present when multiple LLM calls occur
  within one extraction (e.g. VLM OCR + structured extraction).
  """

  @typedoc "Token usage and cost data for a single LLM call made during extraction."
  @type t :: %__MODULE__{
          model: String.t() | nil,
          source: String.t() | nil,
          input_tokens: non_neg_integer() | nil,
          output_tokens: non_neg_integer() | nil,
          total_tokens: non_neg_integer() | nil,
          estimated_cost: float() | nil,
          finish_reason: String.t() | nil
        }

  defstruct model: nil,
            source: nil,
            input_tokens: nil,
            output_tokens: nil,
            total_tokens: nil,
            estimated_cost: nil,
            finish_reason: nil
end
