# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:554349eba5eae52560d71555e2853b160d7b44d4e25854aba5ead23db4010f0f
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.LlmConfig do
  @moduledoc "Configuration for an LLM provider/model via liter-llm."

  defstruct model: nil,
            api_key: nil,
            base_url: nil,
            timeout_secs: 0,
            max_retries: 0,
            temperature: 0.0,
            max_tokens: 0
end
