# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:f1d9a4f3e11a0fb3b3f5a7ba8a0c897768ad230c7d2c8dfef213c1421b13b9fe
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.MetaSchema do
  @moduledoc "Compiled meta-schema validator over `preset.schema.json`."

  alias Kreuzberg.Native
  defstruct [:ref]

  @typedoc "Compiled meta-schema validator over `preset.schema.json`."
  @type t :: %__MODULE__{ref: reference()}

  @doc "Compile the given JSON text as a Draft 2020-12 meta-schema."
  def compile(meta_schema_json) do
    ref = Native.metaschema_compile(meta_schema_json)
    %__MODULE__{ref: ref}
  end

  @doc "Validate `raw` against the meta-schema and deserialize into a [`Preset`],"
  def parse_preset(obj, path, raw) do
    Native.metaschema_parse_preset(obj.ref, path, raw)
  end
end
