# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:7541a932f70a6912fee947204303742ddada87e2682c8ac1505d80862cb41bc5
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.Metadata do
  @moduledoc "Extraction result metadata."

  defstruct title: nil,
            subject: nil,
            authors: [],
            keywords: [],
            language: nil,
            created_at: nil,
            modified_at: nil,
            created_by: nil,
            modified_by: nil,
            pages: nil,
            format: :pdf,
            image_preprocessing: nil,
            json_schema: nil,
            error: nil,
            extraction_duration_ms: 0,
            category: nil,
            tags: [],
            document_version: nil,
            abstract_text: nil,
            output_format: nil,
            ocr_used: false,
            additional: %{}
end
