# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:cc2956f5955ac7e0f45e1cbf24d6d0be14416a6fe22ffe6a694316c85e480044
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.ModelPaths do
  @moduledoc "Combined paths to all models needed for OCR (backward compatibility)."

  @typedoc "Combined paths to all models needed for OCR (backward compatibility)."
  @type t :: %__MODULE__{
          det_model: String.t() | nil,
          cls_model: String.t() | nil,
          rec_model: String.t() | nil,
          dict_file: String.t() | nil
        }

  defstruct det_model: nil,
            cls_model: nil,
            rec_model: nil,
            dict_file: nil
end
