# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:efd2140ced6a009a9d1d38ddc72b4db276a858d7af7ae2532a69917fe8e14cdc
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.ModelPaths do
  @moduledoc "Combined paths to all models needed for OCR (backward compatibility)."

  @typedoc "Combined paths to all models needed for OCR (backward compatibility)."
  @type t :: %__MODULE__{
          det_model: String.t() | nil,
          cls_model: String.t() | nil,
          rec_model: String.t() | nil,
          dict_file: String.t() | nil
        }

  defstruct det_model: nil,
            cls_model: nil,
            rec_model: nil,
            dict_file: nil
end
