# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:caebc3d131b03cb582c1cfce436a09b785978f3583c9aa2c5949daafccaf63ae
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.NerBackendKind do
  @moduledoc "NER backend selector."

  @typedoc "NER backend selector."
  @type t :: :onnx | :llm

  @onnx :onnx
  @llm :llm

  @doc "gline-rs ONNX inference. Requires `ner-onnx` feature. Models download lazily from HuggingFace via `model_download::hf_download`."
  @spec onnx() :: t()
  def onnx, do: @onnx
  @doc "liter-llm zero-shot NER via structured-output prompts. Requires `ner-llm` feature. Useful when domain-specific categories outstrip the ONNX taxonomy."
  @spec llm() :: t()
  def llm, do: @llm
end
