# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:101f93f77893c2c7989723625cc5537a934c702f60a360b93d41055b40c41ceb
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.OcrPipelineConfig do
  @moduledoc """
  Multi-backend OCR pipeline with quality-based fallback.

  Backends are tried in priority order (highest first). After each backend
  produces output, quality is evaluated. If it meets `quality_thresholds.pipeline_min_quality`,
  the result is accepted. Otherwise the next backend is tried.
  """

  @typedoc "Multi-backend OCR pipeline with quality-based fallback."
  @type t :: %__MODULE__{
          stages: [map()],
          quality_thresholds: map()
        }

  defstruct stages: [],
            quality_thresholds: nil
end
