# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a9ceb0b652b7278e70b811b2b2dcbf42a3c23a7ebdc28f72c68b8297badfd716
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.OcrConfidence do
  @moduledoc "Confidence scores for an OCR element."

  @type t :: %__MODULE__{
          detection: float() | nil,
          recognition: float()
        }

  defstruct detection: nil,
            recognition: 0.0
end
