# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:b0d91fb62af08d6df7113b91209e9869bee112506d29e5da63e938bfffebaadf
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/sample_crate-dev/alef
defmodule Kreuzberg.OcrTable do
  @moduledoc """
  Table detected via OCR.

  Represents a table structure recognized during OCR processing.
  """

  @typedoc "Table detected via OCR."
  @type t :: %__MODULE__{
          cells: [[String.t()]],
          markdown: String.t() | nil,
          page_number: non_neg_integer(),
          bounding_box: map() | nil
        }

  defstruct cells: [],
            markdown: nil,
            page_number: 0,
            bounding_box: nil
end
