# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:edb9d69026174ed5c1811f3bcaf9b93a928675ba6cb7515cd60670ed43518d20
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.OcrRotation do
  @moduledoc "Rotation information for an OCR element."

  @type t :: %__MODULE__{
          angle_degrees: float(),
          confidence: float() | nil
        }

  defstruct angle_degrees: 0.0,
            confidence: nil
end
