# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:129f6c78bc96b39658ce61eefcba84c48dda7c11a0dc9f36687849db17ea4295
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.OcrElementConfig do
  @moduledoc """
  Configuration for OCR element extraction.

  Controls how OCR elements are extracted and filtered.
  """

  @typedoc "Configuration for OCR element extraction."
  @type t :: %__MODULE__{
          include_elements: boolean(),
          min_level: String.t() | nil,
          min_confidence: float(),
          build_hierarchy: boolean()
        }

  defstruct include_elements: false,
            min_level: :line,
            min_confidence: 0.0,
            build_hierarchy: false

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
