# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:cc2956f5955ac7e0f45e1cbf24d6d0be14416a6fe22ffe6a694316c85e480044
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.OcrBoundingGeometry do
  @moduledoc """
  Bounding geometry for an OCR element.

  Supports both axis-aligned rectangles (from Tesseract) and 4-point quadrilaterals
  (from PaddleOCR and rotated text detection).
  """

  @typedoc "Bounding geometry for an OCR element."
  @type t :: term()

  @typedoc "Axis-aligned bounding box (typical for Tesseract output)."
  @type rectangle :: %{type: :rectangle, left: non_neg_integer(), top: non_neg_integer(), width: non_neg_integer(), height: non_neg_integer()}
  @typedoc "4-point quadrilateral for rotated/skewed text (PaddleOCR)."
  @type quadrilateral :: %{type: :quadrilateral, points: String.t()}
end
