# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:332c04fb704f288c6aadc54631c61f968478cf0193bab8ec62a21e4dec6c2c0c
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.OcrBoundingGeometry do
  @moduledoc "Bounding geometry for an OCR element."

  @type t :: term()

  @type rectangle :: %{
          type: :rectangle,
          left: non_neg_integer(),
          top: non_neg_integer(),
          width: non_neg_integer(),
          height: non_neg_integer()
        }
  @type quadrilateral :: %{type: :quadrilateral, points: String.t()}
end
