# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:c9dc9b974833d553bda62a8bd0befa85e3f3bcd4123126bb9f835b3c2d82debe
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.OcrPipelineStage do
  @moduledoc "A single backend stage in the OCR pipeline."

  @typedoc "A single backend stage in the OCR pipeline."
  @type t :: %__MODULE__{
          backend: String.t() | nil,
          priority: non_neg_integer(),
          language: String.t() | nil,
          tesseract_config: map() | nil,
          paddle_ocr_config: String.t() | nil,
          vlm_config: map() | nil,
          backend_options: String.t() | nil
        }

  defstruct backend: nil,
            priority: 0,
            language: nil,
            tesseract_config: nil,
            paddle_ocr_config: nil,
            vlm_config: nil,
            backend_options: nil
end
