# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:9d7b9a8f38dfc90c478ba9e2c99487f09c495b558cd0fd2a81ca7ac2768509ec
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.PageBoundary do
  @moduledoc "Byte offset boundary for a page."

  @type t :: %__MODULE__{
          byte_start: non_neg_integer(),
          byte_end: non_neg_integer(),
          page_number: non_neg_integer()
        }

  defstruct byte_start: 0,
            byte_end: 0,
            page_number: 0
end
