# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:9f578f2470bbec7549733c73ae6b7d724fd2f5f58441654ef1d408d21e501c7d
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.PageClassification do
  @moduledoc "Classification result for a single page."

  @typedoc "Classification result for a single page."
  @type t :: %__MODULE__{
          page_number: non_neg_integer(),
          labels: [map()]
        }

  defstruct page_number: 0,
            labels: []
end
