# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:55cf9a5906feb590d69168ad964e432c354c1464aef4b19f04e94317d4a3a74f
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.PageInfo do
  @moduledoc """
  Metadata for individual page/slide/sheet.

  Captures per-page information including dimensions, content counts,
  and visibility state (for presentations).
  """

  @typedoc "Metadata for individual page/slide/sheet."
  @type t :: %__MODULE__{
          number: non_neg_integer(),
          title: String.t() | nil,
          image_count: non_neg_integer() | nil,
          table_count: non_neg_integer() | nil,
          hidden: boolean() | nil,
          is_blank: boolean() | nil,
          has_vector_graphics: boolean()
        }

  defstruct number: 0,
            title: nil,
            image_count: nil,
            table_count: nil,
            hidden: nil,
            is_blank: nil,
            has_vector_graphics: false
end
