# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:740c5012904701fee6acaa339c14e09b8d6aabec4913ba82b7a4ce9124721264
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.PageHierarchy do
  @moduledoc """
  Page hierarchy structure containing heading levels and block information.

  Used when PDF text hierarchy extraction is enabled. Contains hierarchical
  blocks with heading levels (H1-H6) for semantic document structure.
  """

  @typedoc "Page hierarchy structure containing heading levels and block information."
  @type t :: %__MODULE__{
          block_count: non_neg_integer(),
          blocks: [map()]
        }

  defstruct block_count: 0,
            blocks: []
end
