# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:9f578f2470bbec7549733c73ae6b7d724fd2f5f58441654ef1d408d21e501c7d
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.PageStructure do
  @moduledoc """
  Unified page structure for documents.

  Supports different page types (PDF pages, PPTX slides, Excel sheets)
  with character offset boundaries for chunk-to-page mapping.
  """

  @typedoc "Unified page structure for documents."
  @type t :: %__MODULE__{
          total_count: non_neg_integer(),
          unit_type: String.t() | nil,
          boundaries: [map()] | nil,
          pages: [map()] | nil
        }

  defstruct total_count: 0,
            unit_type: :page,
            boundaries: nil,
            pages: nil
end
