# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:1ea2e31be2ea3875c4ac7b04e7c0c6025863bc99d4f62123c28991d3b085a679
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.PdfAnnotation do
  @moduledoc "A PDF annotation extracted from a document page."

  @typedoc "A PDF annotation extracted from a document page."
  @type t :: %__MODULE__{
          annotation_type: String.t() | nil,
          content: String.t() | nil,
          page_number: non_neg_integer(),
          bounding_box: map() | nil
        }

  defstruct annotation_type: :text,
            content: nil,
            page_number: 0,
            bounding_box: nil
end
