# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:cc2956f5955ac7e0f45e1cbf24d6d0be14416a6fe22ffe6a694316c85e480044
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.PiiCategory do
  @moduledoc "PII categories the pattern engine recognises."

  @typedoc "PII categories the pattern engine recognises."
  @type t :: term()

  @type email :: :email
  @type phone :: :phone
  @type ssn :: :ssn
  @type credit_card :: :credit_card
  @type postal_code :: :postal_code
  @type ip_address :: :ip_address
  @type iban :: :iban
  @type swift_bic :: :swift_bic
  @type date_of_birth :: :date_of_birth
  @typedoc "Person name, surfaced by the optional NER backend."
  @type person :: :person
  @typedoc "Organization name, surfaced by the optional NER backend."
  @type organization :: :organization
  @typedoc "Location, surfaced by the optional NER backend."
  @type location :: :location
  @typedoc "Caller-supplied custom category (e.g. internal employee IDs)."
  @type custom :: %{type: :custom, value: String.t()}
end
