# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:f1d9a4f3e11a0fb3b3f5a7ba8a0c897768ad230c7d2c8dfef213c1421b13b9fe
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.PresetSummary do
  @moduledoc """
  Lightweight projection of [`Preset`] used by the registry list endpoint
  (omits the full schema and prompt to keep the payload small).
  """

  @typedoc "Lightweight projection of [`Preset`] used by the registry list endpoint (omits the full schema and prompt to keep the payload small)."
  @type t :: %__MODULE__{
          id: String.t() | nil,
          version: String.t() | nil,
          schema_name: String.t() | nil,
          description: String.t() | nil,
          category: String.t() | nil,
          tags: [String.t()],
          preferred_call_mode: String.t() | nil,
          emit_citations: boolean(),
          fingerprint: String.t() | nil
        }

  defstruct id: nil,
            version: nil,
            schema_name: nil,
            description: nil,
            category: :finance,
            tags: [],
            preferred_call_mode: :text_only,
            emit_citations: false,
            fingerprint: nil
end
