# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:c9dc9b974833d553bda62a8bd0befa85e3f3bcd4123126bb9f835b3c2d82debe
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.PstMetadata do
  @moduledoc "Outlook PST archive metadata."

  @typedoc "Outlook PST archive metadata."
  @type t :: %__MODULE__{
          message_count: non_neg_integer()
        }

  defstruct message_count: 0

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
