# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:b70ce7a0d6fd9a50f9fd5858a78cee95ca08be04e2fe86e9dc1f3ad995253c01
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.RecognizedTable do
  @moduledoc "Pre-computed table markdown for a table detection region."

  defstruct detection_bbox: nil,
            cells: [],
            markdown: nil
end
