# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:1ea2e31be2ea3875c4ac7b04e7c0c6025863bc99d4f62123c28991d3b085a679
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.RedactionTerm do
  @moduledoc """
  One user-supplied literal term to redact.

  Matched as a regex-escaped substring (so callers do not need to escape
  metacharacters themselves). Case-insensitive by default — set
  [`Self::case_sensitive`] to `true` for exact byte-match semantics.
  """

  @typedoc "One user-supplied literal term to redact."
  @type t :: %__MODULE__{
          label: String.t() | nil,
          value: String.t() | nil,
          case_sensitive: boolean()
        }

  defstruct label: nil,
            value: nil,
            case_sensitive: false
end
