# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:cc2956f5955ac7e0f45e1cbf24d6d0be14416a6fe22ffe6a694316c85e480044
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.RedactionTerm do
  @moduledoc """
  One user-supplied literal term to redact.

  Matched as a regex-escaped substring (so callers do not need to escape
  metacharacters themselves). Case-insensitive by default — set
  [`Self::case_sensitive`] to `true` for exact byte-match semantics.
  """

  @typedoc "One user-supplied literal term to redact."
  @type t :: %__MODULE__{
          label: String.t() | nil,
          value: String.t() | nil,
          case_sensitive: boolean()
        }

  defstruct label: nil,
            value: nil,
            case_sensitive: false
end
