# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:f1d9a4f3e11a0fb3b3f5a7ba8a0c897768ad230c7d2c8dfef213c1421b13b9fe
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.RegionKind do
  @moduledoc """
  Classification of a detected layout region that warrants VLM extraction.

  Each variant maps to a specific prompt optimised for that content type.
  The mapping is intentionally narrow — only region kinds for which VLM
  extraction provides a clear quality benefit over classical suppression.
  """

  @typedoc "Classification of a detected layout region that warrants VLM extraction."
  @type t :: :figure | :dense_table | :complex_layout | :caption

  @figure :figure
  @dense_table :dense_table
  @complex_layout :complex_layout
  @caption :caption

  @doc "A figure, diagram, chart, or image region."
  @spec figure() :: t()
  def figure, do: @figure
  @doc "A densely formatted or complex table that classical extraction garbles."
  @spec dense_table() :: t()
  def dense_table, do: @dense_table
  @doc "A region whose layout the classical pipeline cannot handle (multi-column insets, heavily annotated forms, mixed text+diagram)."
  @spec complex_layout() :: t()
  def complex_layout, do: @complex_layout
  @doc "A standalone image to be captioned (not extracted as figure markdown)."
  @spec caption() :: t()
  def caption, do: @caption
end
