# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:6a863205e7a486a4e1b97dac288554ebbf65a8b3ad1aaa6799965109e6543cd4
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.RevisionDelta do
  @moduledoc """
  The content changes that make up a single revision.

  For insertions and deletions the `content` field carries the added/removed
  lines as `DiffLine::Added` / `DiffLine::Removed` entries. For format
  changes, `content` is empty — the property diff is left as a TODO for a
  later enrichment pass.
  """

  @typedoc "The content changes that make up a single revision."
  @type t :: %__MODULE__{
          content: [String.t() | nil],
          table_changes: [map()]
        }

  defstruct content: [],
            table_changes: []

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
