# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:78731a9cb72bc03959c80f9b29276f361cdbfa22495cf9dd154c9bc8940a19a5
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ServerConfig do
  @moduledoc "API server configuration."

  @type t :: %__MODULE__{
          host: String.t() | nil,
          port: non_neg_integer(),
          cors_origins: [String.t()],
          max_request_body_bytes: non_neg_integer(),
          max_multipart_field_bytes: non_neg_integer()
        }

  defstruct host: nil,
            port: 0,
            cors_origins: [],
            max_request_body_bytes: 0,
            max_multipart_field_bytes: 0
end
