# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:1dfb39df4e7e978b60e3e20bde8c1780a3bdce0722a2a368c3cdb6e3bc312bf7
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ServerConfig do
  @moduledoc "API server configuration."

  defstruct host: nil,
            port: 0,
            cors_origins: [],
            max_request_body_bytes: 0,
            max_multipart_field_bytes: 0
end
