# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:339791dc1f2c3c142bb19edbc3cb364ed20166ad0f3647e1e64209c96d3f86e9
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.SupportedFormat do
  @moduledoc "A supported document format entry."

  defstruct extension: "",
            mime_type: ""
end
