# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:e88db22527e04217d83998801694e2f51addebed378a36944d87f5c15c57ab86
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.SupportedFormat do
  @moduledoc "A supported document format entry."

  defstruct extension: nil,
            mime_type: nil
end
