# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:fc80bf10cd9e5e7f08a9c541fcd6220d7342df63fa1e17d6ecf17827e285a57b
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.TableDiff do
  @moduledoc "Cell-level changes for a pair of tables that share the same index."

  @typedoc "Cell-level changes for a pair of tables that share the same index."
  @type t :: %__MODULE__{
          from_index: non_neg_integer(),
          to_index: non_neg_integer(),
          cell_changes: [map()]
        }

  defstruct from_index: 0,
            to_index: 0,
            cell_changes: []
end
