# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:cd47a123c15e81eb202883752dbbe1e3b79560af4262761373429c24f46af3f1
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.TableGrid do
  @moduledoc """
  Structured table grid with cell-level metadata.

  Stores row/column dimensions and a flat list of cells with position info.
  """

  @typedoc "Structured table grid with cell-level metadata."
  @type t :: %__MODULE__{
          rows: non_neg_integer(),
          cols: non_neg_integer(),
          cells: [map()]
        }

  defstruct rows: 0,
            cols: 0,
            cells: []

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
