# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:6a8400ffd6e27c557ffd585458e080034774f33340cc49f53c2cb322a0da85dd
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.TextMetadata do
  @moduledoc """
  Text/Markdown metadata.

  Extracted from plain text and Markdown files. Includes word counts and,
  for Markdown, structural elements like headers and links.
  """

  @typedoc "Text/Markdown metadata."
  @type t :: %__MODULE__{
          line_count: non_neg_integer(),
          word_count: non_neg_integer(),
          character_count: non_neg_integer(),
          headers: [String.t()] | nil
        }

  defstruct line_count: 0,
            word_count: 0,
            character_count: 0,
            headers: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
