# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:740c5012904701fee6acaa339c14e09b8d6aabec4913ba82b7a4ce9124721264
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.TextAnnotation do
  @moduledoc """
  Inline text annotation — byte-range based formatting and links.

  Annotations reference byte offsets into the node's text content,
  enabling precise identification of formatted regions.
  """

  @typedoc "Inline text annotation — byte-range based formatting and links."
  @type t :: %__MODULE__{
          start: non_neg_integer(),
          end: non_neg_integer(),
          kind: String.t() | nil
        }

  defstruct start: 0,
            end: 0,
            kind: :bold
end
