# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:f1d9a4f3e11a0fb3b3f5a7ba8a0c897768ad230c7d2c8dfef213c1421b13b9fe
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.TokenCounter do
  @moduledoc "Per-category running counter for [`RedactionStrategy::TokenReplace`]."

  alias Kreuzberg.Native
  defstruct [:ref]

  @typedoc "Per-category running counter for [`RedactionStrategy::TokenReplace`]."
  @type t :: %__MODULE__{ref: reference()}

  @doc "Build a default instance."
  @spec new() :: t()
  def new do
    %__MODULE__{ref: Native.tokencounter_default()}
  end
  def default() do
    ref = Native.tokencounter_default()
    %__MODULE__{ref: ref}
  end
end
