# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:fc80bf10cd9e5e7f08a9c541fcd6220d7342df63fa1e17d6ecf17827e285a57b
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.TokenReductionOptions do
  @moduledoc "Token reduction configuration."

  @typedoc "Token reduction configuration."
  @type t :: %__MODULE__{
          mode: String.t() | nil,
          preserve_important_words: boolean()
        }

  defstruct mode: nil,
            preserve_important_words: true

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
