# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:55cf9a5906feb590d69168ad964e432c354c1464aef4b19f04e94317d4a3a74f
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.Translation do
  @moduledoc """
  Translation of the extracted content.

  Holds the translated rendition of `ExtractionResult::content` and (when
  `preserve_markup` was requested) the translated `formatted_content`. Chunks
  are translated in place inside `ExtractionResult::chunks[*].content` rather
  than duplicated here.
  """

  @typedoc "Translation of the extracted content."
  @type t :: %__MODULE__{
          target_lang: String.t() | nil,
          source_lang: String.t() | nil,
          content: String.t() | nil,
          formatted_content: String.t() | nil
        }

  defstruct target_lang: nil,
            source_lang: nil,
            content: nil,
            formatted_content: nil
end
