# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:740c5012904701fee6acaa339c14e09b8d6aabec4913ba82b7a4ce9124721264
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.TranslationConfig do
  @moduledoc "Configuration for the translation post-processor."

  @typedoc "Configuration for the translation post-processor."
  @type t :: %__MODULE__{
          target_lang: String.t() | nil,
          source_lang: String.t() | nil,
          preserve_markup: boolean(),
          llm: map()
        }

  defstruct target_lang: nil,
            source_lang: nil,
            preserve_markup: false,
            llm: nil
end
