# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:0f7fbbeba0e5135e31daa45ca7b235ae6cdd3b4be0420d17aab108e03f395bdc
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.Uri do
  @moduledoc "A URI extracted from a document."

  defstruct url: "",
            label: nil,
            page: nil,
            kind: :hyperlink
end
