# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:cd47a123c15e81eb202883752dbbe1e3b79560af4262761373429c24f46af3f1
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.UserChunkConfig do
  @moduledoc "User-provided chunk configuration."

  @typedoc "User-provided chunk configuration."
  @type t :: %__MODULE__{
          page_ranges: [map()] | nil,
          pages_per_chunk: non_neg_integer() | nil,
          force_chunking: boolean(),
          disable_chunking: boolean()
        }

  defstruct page_ranges: nil,
            pages_per_chunk: nil,
            force_chunking: false,
            disable_chunking: false

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
