# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:f8f967fc48aebabd836fde91ece74179c1678f8fa1e8f4d074cecd1adcc8d872
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.WarmResponse do
  @moduledoc "Cache warm response."

  defstruct cache_dir: nil,
            downloaded: [],
            already_cached: []
end
