# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:af29a8432a7d57b52d6e4a23f477a6151dc1805cdff0497b59726d1b10a2787b
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.WarmResponse do
  @moduledoc "Cache warm response."

  defstruct cache_dir: "",
            downloaded: [],
            already_cached: []
end
