# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:65117d288912e7df5e977f99f2d09efab54c6797514ab3e309dac9b711595575
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.YearRange do
  @moduledoc "Year range for bibliographic metadata."

  @typedoc "Year range for bibliographic metadata."
  @type t :: %__MODULE__{
          min: non_neg_integer() | nil,
          max: non_neg_integer() | nil,
          years: [non_neg_integer()]
        }

  defstruct min: nil,
            max: nil,
            years: []
end
