// DO NOT EDIT - auto-generated by alef
// alef:hash:c1dfa38f25cb4a4f3ae999d5f20b3224282c944b5460083a05218399c26fa935
package io.xberg;

/**
 * The meta-schema itself failed to compile.
 */
public class BadMetaSchemaException extends LoadErrorException {
    private static final long serialVersionUID = 1L;

    /** Creates a new BadMetaSchemaException with the given message. */
    public BadMetaSchemaException(final String message) {
        super(message);
    }

    /** Creates a new BadMetaSchemaException with the given message and cause. */
    public BadMetaSchemaException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
