// DO NOT EDIT - auto-generated by alef
// alef:hash:10f69d3922c038c3f3397ab775fa7c70016151a1f97a547ab8ea739f743a5288
package io.xberg;

/**
 * The extraction was cancelled via a `CancellationToken`.
 */
public class CancelledException extends XbergErrorException {
    private static final long serialVersionUID = 1L;

    /** Creates a new CancelledException with the given message. */
    public CancelledException(final String message) {
        super(message);
    }

    /** Creates a new CancelledException with the given message and cause. */
    public CancelledException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
