// DO NOT EDIT - auto-generated by alef
// alef:hash:38dce430f8d9bea3dcf8465197cc598552462cd7a5930cc5e7e769e1d0990c01
package io.xberg;

/**
 * Errors that can occur during heuristics analysis.
 */
public class HeuristicsErrorException extends Exception {
    private static final long serialVersionUID = 1L;
    /** Creates a new HeuristicsErrorException with the given message. */
    public HeuristicsErrorException(final String message) {
        super(message);
    }

    /** Creates a new HeuristicsErrorException with the given message and cause. */
    public HeuristicsErrorException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
