// DO NOT EDIT - auto-generated by alef
// alef:hash:10f69d3922c038c3f3397ab775fa7c70016151a1f97a547ab8ea739f743a5288
package io.xberg;

/**
 * A catch-all for uncommon errors that do not fit another variant.
 */
public class OtherException extends XbergErrorException {
    private static final long serialVersionUID = 1L;

    /** Creates a new OtherException with the given message. */
    public OtherException(final String message) {
        super(message);
    }

    /** Creates a new OtherException with the given message and cause. */
    public OtherException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
