// DO NOT EDIT - auto-generated by alef
// alef:hash:10f69d3922c038c3f3397ab775fa7c70016151a1f97a547ab8ea739f743a5288
package io.xberg;

/**
 * The reranker model or reranking pipeline returned an error.
 *
 * Since v5.0.0.
 */
public class RerankingException extends XbergErrorException {
    private static final long serialVersionUID = 1L;

    /** Creates a new RerankingException with the given message. */
    public RerankingException(final String message) {
        super(message);
    }

    /** Creates a new RerankingException with the given message and cause. */
    public RerankingException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
