// DO NOT EDIT - auto-generated by alef
// alef:hash:0ce3ea7bbabccafc622b4dd87ac0f00356dd0426ec66977c856525dabafdc585
package io.xberg;

/**
 * JSON or MessagePack serialization/deserialization failed.
 */
public class SerializationException extends XbergErrorException {
    private static final long serialVersionUID = 1L;

    /** Creates a new SerializationException with the given message. */
    public SerializationException(final String message) {
        super(message);
    }

    /** Creates a new SerializationException with the given message and cause. */
    public SerializationException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
