// DO NOT EDIT - auto-generated by alef
// alef:hash:0ce3ea7bbabccafc622b4dd87ac0f00356dd0426ec66977c856525dabafdc585
package io.xberg;

/**
 * The extraction operation exceeded the configured time limit.
 */
public class TimeoutException extends XbergErrorException {
    private static final long serialVersionUID = 1L;

    /** Creates a new TimeoutException with the given message. */
    public TimeoutException(final String message) {
        super(message);
    }

    /** Creates a new TimeoutException with the given message and cause. */
    public TimeoutException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
