// DO NOT EDIT - auto-generated by alef
// alef:hash:c1dfa38f25cb4a4f3ae999d5f20b3224282c944b5460083a05218399c26fa935
package io.xberg;

/**
 * Audio/video transcription failed.
 */
public class TranscriptionException extends XbergErrorException {
    private static final long serialVersionUID = 1L;

    /** Creates a new TranscriptionException with the given message. */
    public TranscriptionException(final String message) {
        super(message);
    }

    /** Creates a new TranscriptionException with the given message and cause. */
    public TranscriptionException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
