// DO NOT EDIT - auto-generated by alef
// alef:hash:356ed0ad572128a92e2a68ca531b92cd783973ff49e6e7f17fef8212f0216bcf
package io.xberg;

/**
 * The document's MIME type is not supported by any registered extractor.
 */
public class UnsupportedFormatException extends XbergErrorException {
    private static final long serialVersionUID = 1L;

    /** Creates a new UnsupportedFormatException with the given message. */
    public UnsupportedFormatException(final String message) {
        super(message);
    }

    /** Creates a new UnsupportedFormatException with the given message and cause. */
    public UnsupportedFormatException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
