# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:f1d9a4f3e11a0fb3b3f5a7ba8a0c897768ad230c7d2c8dfef213c1421b13b9fe
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# frozen_string_literal: true

require 'spec_helper'
require 'kreuzberg'
require 'json'

RSpec.describe 'post_processor_management' do
  it 'post_processors_clear: Clear all post-processors and verify list is empty' do
    Kreuzberg.clear_post_processors()

  end

  it 'post_processors_list: List all registered post-processors' do
    result = Kreuzberg.list_post_processors()

    expect(result).not_to be_nil
  end
end
