# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:740c5012904701fee6acaa339c14e09b8d6aabec4913ba82b7a4ce9124721264
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# frozen_string_literal: true

require 'spec_helper'
require 'kreuzberg'
require 'json'

RSpec.describe 'registry' do
  it 'list_document_extractors: List document extractors' do
    result = Kreuzberg.list_document_extractors()

    expect(result).not_to be_nil
  end

  it 'list_embedding_backends: List embedding backends' do
    result = Kreuzberg.list_embedding_backends()

    expect(result).not_to be_nil
  end

  it 'list_ocr_backends: List OCR backends' do
    result = Kreuzberg.list_ocr_backends()

    expect(result).not_to be_nil
  end

  it 'list_post_processors: List post-processors' do
    result = Kreuzberg.list_post_processors()

    expect(result).not_to be_nil
  end

  it 'list_renderers: List renderers' do
    result = Kreuzberg.list_renderers()

    expect(result).not_to be_nil
  end

  it 'list_validators: List validators' do
    result = Kreuzberg.list_validators()

    expect(result).not_to be_nil
  end
end
