# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:1ea2e31be2ea3875c4ac7b04e7c0c6025863bc99d4f62123c28991d3b085a679
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# frozen_string_literal: true

require 'kreuzberg'
require 'json'
require 'spec_helper'

RSpec.describe 'renderer_management' do
  it 'renderers_clear: Clear all renderers and verify list is empty' do
    Kreuzberg.clear_renderers()

  end

  it 'renderers_list: List all registered renderers' do
    result = Kreuzberg.list_renderers()

    expect(result).not_to be_nil
  end
end
