# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:cd47a123c15e81eb202883752dbbe1e3b79560af4262761373429c24f46af3f1
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# frozen_string_literal: true

require 'spec_helper'
require 'kreuzberg'
require 'json'

RSpec.describe 'rerank_async_pending' do
  it 'async_rerank: rerank_async: plugin model with no backend registered returns an error' do
    expect {
      Kreuzberg.rerank_async('neural networks', ['Neural networks are a class of machine learning models inspired by biological brains.', 'The Eiffel Tower is located in Paris.', 'Convolutional neural networks excel at image recognition tasks.'], {model: { 'name' => 'async_rerank', 'type' => 'plugin' }})
    }.to raise_error(RuntimeError)
  end
end
