# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:38dce430f8d9bea3dcf8465197cc598552462cd7a5930cc5e7e769e1d0990c01
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# frozen_string_literal: true

require 'spec_helper'
require 'xberg'
require 'json'

RSpec.describe 'tokenizer_backend_management' do
  it 'tokenizer_backends_clear: Clear all tokenizer backends and verify list is empty' do
    Xberg.clear_tokenizer_backends()

  end

  it 'tokenizer_backends_list: List all registered tokenizer backends' do
    result = Xberg.list_tokenizer_backends()

    expect(result).not_to be_nil
  end
end
