# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:6a863205e7a486a4e1b97dac288554ebbf65a8b3ad1aaa6799965109e6543cd4
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# frozen_string_literal: true

require 'spec_helper'
require 'kreuzberg'
require 'json'

RSpec.describe 'validator_management' do
  it 'validators_clear: Clear all validators and verify list is empty' do
    Kreuzberg.clear_validators()

  end

  it 'validators_list: List all registered validators' do
    result = Kreuzberg.list_validators()

    expect(result).not_to be_nil
  end
end
