# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:932c299e263134c4cc188f80ca1d81c1eca95f4378df129af6ff63176a4ee7ed
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/sample_crate-dev/alef
# frozen_string_literal: true

require 'kreuzberg'
require 'json'
require 'spec_helper'

RSpec.describe 'validator_management' do
  it 'validators_clear: Clear all validators and verify list is empty' do
    Kreuzberg.clear_validators()

  end

  it 'validators_list: List all registered validators' do
    result = Kreuzberg.list_validators()

    expect(result).not_to be_nil
  end
end
