// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:c9dc9b974833d553bda62a8bd0befa85e3f3bcd4123126bb9f835b3c2d82debe
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code

// E2e tests for category: document_extractor_management
package e2e_test

import (
	"testing"

	kreuzberg "github.com/kreuzberg-dev/kreuzberg/v5"
)

func Test_DocumentExtractorsClear(t *testing.T) {
	// Clear all document extractors and verify list is empty
	_ = kreuzberg.ClearDocumentExtractors()
}

func Test_ExtractorsList(t *testing.T) {
	// List all registered document extractors
	_, err := kreuzberg.ListDocumentExtractors()
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}
