// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:c1dfa38f25cb4a4f3ae999d5f20b3224282c944b5460083a05218399c26fa935
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code

// E2e tests for category: validator_management
package e2e_test

import (
	"testing"

	xberg "github.com/xberg-io/xberg"
)

func Test_ValidatorsClear(t *testing.T) {
	// Clear all validators and verify list is empty
	_ = xberg.ClearValidators()
}

func Test_ValidatorsList(t *testing.T) {
	// List all registered validators
	_, err := xberg.ListValidators()
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}
