// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:aad1613ab2bed9c07ecae237e4d98ad14326e98ca8ca5d24048b88dbd3cb0c2b
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.e2e

import org.junit.jupiter.api.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue
import kotlin.test.assertFalse
import kotlin.test.assertFailsWith
import kotlinx.coroutines.runBlocking
import dev.kreuzberg.Kreuzberg

/** E2e tests for category: detection. */
class DetectionTest {
    @Test
    fun testDetectMimeBytesHtml() = runBlocking {
        // Detect HTML MIME from bytes
        val result = Kreuzberg.detectMimeTypeFromBytes(java.nio.file.Files.readAllBytes(java.nio.file.Path.of("html/html.html")))
    }

    @Test
    fun testDetectMimeBytesPdf() = runBlocking {
        // Detect PDF MIME type from bytes
        val result = Kreuzberg.detectMimeTypeFromBytes(java.nio.file.Files.readAllBytes(java.nio.file.Path.of("pdf/fake_memo.pdf")))
    }

    @Test
    fun testDetectMimeBytesPng() = runBlocking {
        // Detect PNG MIME type from bytes
        val result = Kreuzberg.detectMimeTypeFromBytes(java.nio.file.Files.readAllBytes(java.nio.file.Path.of("images/test_hello_world.png")))
    }

    @Test
    fun testGetExtensionsUnknownMime() = runBlocking {
        // get_extensions unknown MIME
        assertFailsWith<Exception> {
            Kreuzberg.getExtensionsForMime("application/x-totally-unknown")
        }
    }

}
