// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:9f578f2470bbec7549733c73ae6b7d724fd2f5f58441654ef1d408d21e501c7d
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package dev.kreuzberg.e2e

import org.junit.jupiter.api.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue
import kotlin.test.assertFalse
import kotlin.test.assertFailsWith
import kotlinx.coroutines.runBlocking
import dev.kreuzberg.Kreuzberg

/** E2e tests for category: embedding_backend_management. */
class EmbeddingBackendManagementTest {
    @Test
    fun testEmbeddingBackendsClear() = runBlocking {
        // Clear all embedding backends and verify list is empty
        val result = EmbeddingBackendBridge.clearAll()
    }

    @Test
    fun testEmbeddingBackendsList() = runBlocking {
        // List all registered embedding backends
        val result = Kreuzberg.listEmbeddingBackends()
    }

}
