// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:cc2956f5955ac7e0f45e1cbf24d6d0be14416a6fe22ffe6a694316c85e480044
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package dev.kreuzberg.e2e

import org.junit.jupiter.api.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue
import kotlin.test.assertFalse
import kotlin.test.assertFailsWith
import kotlinx.coroutines.runBlocking
import dev.kreuzberg.Kreuzberg

/** E2e tests for category: embedding_backend_management. */
class EmbeddingBackendManagementTest {
    @Test
    fun testEmbeddingBackendsClear() = runBlocking {
        // Clear all embedding backends and verify list is empty
        val result = EmbeddingBackendBridge.clearAll()
    }

    @Test
    fun testEmbeddingBackendsList() = runBlocking {
        // List all registered embedding backends
        val result = Kreuzberg.listEmbeddingBackends()
    }

}
