// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:932c299e263134c4cc188f80ca1d81c1eca95f4378df129af6ff63176a4ee7ed
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/sample_crate-dev/alef
package dev.kreuzberg.e2e

import org.junit.jupiter.api.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue
import kotlin.test.assertFalse
import kotlin.test.assertFailsWith
import kotlinx.coroutines.runBlocking
import dev.kreuzberg.Kreuzberg

/** E2e tests for category: validator_management. */
class ValidatorManagementTest {
    @Test
    fun testValidatorsList() = runBlocking {
        // List all registered validators
        val result = Kreuzberg.listValidators()
    }

}
